{
 "title": "Test-Cluster-Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(FIDel_cluster_status, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Services Port Status",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "block",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "\ncount(probe_success{group=\"milevadb\"} == 1)",
       "legendFormat": "MilevaDB"
      },
      {
       "expr": "\ncount(probe_success{group=\"fidel\"} == 1)",
       "legendFormat": "FIDel"
      },
      {
       "expr": "\ncount(probe_success{group=\"einsteindb\"} == 1)",
       "legendFormat": "EinsteinDB"
      },
      {
       "expr": "\ncount(probe_success{group=\"tiflash\"} == 1)",
       "legendFormat": "TiFlash"
      },
      {
       "expr": "\ncount(probe_success{group=\"pump\"} == 1)",
       "legendFormat": "Pump"
      },
      {
       "expr": "\ncount(probe_success{group=\"drainer\"} == 1)",
       "legendFormat": "Drainer"
      },
      {
       "expr": "\ncount(probe_success{group=\"kafka\"} == 1)",
       "legendFormat": "Kafka"
      },
      {
       "expr": "\ncount(probe_success{group=\"zookeeper\"} == 1)",
       "legendFormat": "Zookeeper"
      },
      {
       "expr": "\ncount(probe_success{group=\"node_exporter\"} == 1)",
       "legendFormat": "Node_exporter"
      },
      {
       "expr": "\ncount(probe_success{group=\"blackbox_exporter\"} == 1)",
       "legendFormat": "Blackbox_exporter"
      },
      {
       "expr": "\ncount(probe_success{group=\"grafana\"} == 1)",
       "legendFormat": "Grafana"
      },
      {
       "expr": "\ncount(probe_success{job=\"blackbox_exporter_http\"} == 1)",
       "legendFormat": "Pushgateway"
      },
      {
       "expr": "\ncount(probe_success{group=\"kafka_exporter\"} == 1)",
       "legendFormat": "Kafka_exporter"
      }
     ]
    },
    {
     "type": "block",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "\ncount(probe_success{group=\"milevadb\"} == 0)",
       "legendFormat": "MilevaDB"
      },
      {
       "expr": "\ncount(probe_success{group=\"fidel\"} == 0)",
       "legendFormat": "FIDel"
      },
      {
       "expr": "\ncount(probe_success{group=\"einsteindb\"} == 0)",
       "legendFormat": "EinsteinDB"
      },
      {
       "expr": "\ncount(probe_success{group=\"tiflash\"} == 0)",
       "legendFormat": "TiFlash"
      },
      {
       "expr": "\ncount(probe_success{group=\"pump\"} == 0)",
       "legendFormat": "Pump"
      },
      {
       "expr": "\ncount(probe_success{group=\"drainer\"} == 0)",
       "legendFormat": "Drainer"
      },
      {
       "expr": "\ncount(probe_success{group=\"kafka\"} == 0)",
       "legendFormat": "Kafka"
      },
      {
       "expr": "\ncount(probe_success{group=\"zookeeper\"} == 0)",
       "legendFormat": "Zookeeper"
      },
      {
       "expr": "\ncount(probe_success{group=\"node_exporter\"} == 0)",
       "legendFormat": "Node_exporter"
      },
      {
       "expr": "\ncount(probe_success{group=\"blackbox_exporter\"} == 0)",
       "legendFormat": "Blackbox_exporter"
      },
      {
       "expr": "\ncount(probe_success{group=\"grafana\"} == 0)",
       "legendFormat": "Grafana"
      },
      {
       "expr": "\ncount(probe_success{job=\"blackbox_exporter_http\"} == 0)",
       "legendFormat": "Pushgateway"
      },
      {
       "expr": "\ncount(probe_success{group=\"kafka_exporter\"} == 0)",
       "legendFormat": "Kafka_exporter"
      }
     ]
    }
   ]
  },
  {
   "title": "FIDel",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "FIDel role",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "delta(FIDel_tso_events{type=\"save\",instance=\"$instance\"}[1m]) > bool 0"
      }
     ]
    },
    {
     "title": "CausetStorage capacity",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 2 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "FIDel_cluster_status{instance=\"$instance\",type=\"storage_capacity\"}"
      }
     ]
    },
    {
     "title": "Current storage size",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 2 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "FIDel_cluster_status{instance=\"$instance\",type=\"storage_size\"}"
      }
     ]
    },
    {
     "title": "Number of Regions",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "FIDel_cluster_status{instance=\"$instance\", type=\"leader_count\"}"
      }
     ]
    },
    {
     "title": "Normal stores",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(FIDel_cluster_status{instance=\"$instance\", type=\"store_up_count\"})"
      }
     ]
    },
    {
     "title": "Abnormal stores",
     "type": "block",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 2 },
     "targets": [
      {
       "expr": "sum(FIDel_cluster_status{instance=\"$instance\", type=\"store_disconnected_count\"})",
       "legendFormat": "Disconnect Stores"
      },
      {
       "expr": "sum(FIDel_cluster_status{instance=\"$instance\", type=\"store_unhealth_count\"})",
       "legendFormat": "Unhealth Stores"
      },
      {
       "expr": "sum(FIDel_cluster_status{instance=\"$instance\", type=\"store_low_space_count\"})",
       "legendFormat": "LowSpace Stores"
      },
      {
       "expr": "sum(FIDel_cluster_status{instance=\"$instance\", type=\"store_down_count\"})",
       "legendFormat": "Down Stores"
      },
      {
       "expr": "sum(FIDel_cluster_status{instance=\"$instance\", type=\"store_offline_count\"})",
       "legendFormat": "Offline Stores"
      },
      {
       "expr": "sum(FIDel_cluster_status{instance=\"$instance\", type=\"store_tombstone_count\"})",
       "legendFormat": "Tombstone Stores"
      }
     ]
    },
    {
     "title": "99% completed cmds duration seconds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{instance=\"$instance\"}[5m])) by (grpc_method, le))",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Handle requests duration seconds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.98, sum(rate(FIDel_client_request_handle_requests_duration_seconds_bucket[30s])) by (type, le))",
       "legendFormat": "{{type}}-98%"
      },
      {
       "expr": "avg(rate(FIDel_client_request_handle_requests_duration_seconds_sum[30s])) by (type) /  avg(rate(FIDel_client_request_handle_requests_duration_seconds_count[30s])) by (type)",
       "legendFormat": "{{type}}-average"
      }
     ]
    },
    {
     "title": "Region health",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "FIDel_regions_status{instance=\"$instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Hot write Region's leader distribution",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "FIDel_hotspot_status{instance=\"$instance\",type=\"hot_write_region_as_leader\"}",
       "legendFormat": "causetstore-{{causetstore}}"
      }
     ]
    },
    {
     "title": "Hot read Region's leader distribution",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "FIDel_hotspot_status{instance=\"$instance\",type=\"hot_read_region_as_leader\"}",
       "legendFormat": "causetstore-{{causetstore}}"
      }
     ]
    },
    {
     "title": "Region heartbeat report",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(FIDel_scheduler_region_heartbeat{instance=\"$instance\", type=\"report\", status=\"ok\"}[1m])) by (causetstore)",
       "legendFormat": "causetstore-{{causetstore}}"
      }
     ]
    },
    {
     "title": "99% Region heartbeat latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(FIDel_scheduler_region_heartbeat_latency_seconds_bucket[5m])) by (causetstore, le))",
       "legendFormat": "causetstore-{{causetstore}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MilevaDB",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Statement OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_executor_statement_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "80"
      }
     ]
    },
    {
     "title": "CPS By Instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(milevadb_server_query_total[1m])",
       "legendFormat": "{{instance}} {{type}} {{result}}"
      }
     ]
    },
    {
     "title": "Failed Query OPM",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milevadb_server_execute_error_total[1m])) by (type)",
       "legendFormat": " {{type}}"
      }
     ]
    },
    {
     "title": "Connection Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "milevadb_server_connections", "legendFormat": "{{instance}}" },
      {
       "expr": "sum(milevadb_server_connections)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"milevadb\"}",
       "legendFormat": "process-{{instance}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"milevadb\"}",
       "legendFormat": "HeapInuse-{{instance}}"
      }
     ]
    },
    {
     "title": "Transaction OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_stochastik_transaction_duration_seconds_count[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Transaction Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_stochastik_transaction_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_stochastik_transaction_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_stochastik_transaction_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "80"
      }
     ]
    },
    {
     "title": "KV Cmd OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_txn_cmd_duration_seconds_count[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Cmd Duration 99",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_einsteindbclient_txn_cmd_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "FIDel TSO OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(FIDel_client_cmd_handle_cmds_duration_seconds_count{type=\"tso\"}[1m]))",
       "legendFormat": "cmd"
      },
      {
       "expr": "sum(rate(FIDel_client_request_handle_requests_duration_seconds_count{type=\"tso\"}[1m]))",
       "legendFormat": "request"
      }
     ]
    },
    {
     "title": "FIDel TSO Wait Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(FIDel_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(FIDel_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(FIDel_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "90"
      }
     ]
    },
    {
     "title": "TiClient Region Error OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_region_err_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Lock Resolve OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_lock_resolver_actions_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Load Schema Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_petri_load_schema_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "KV Backoff OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_backoff_seconds_count[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "EinsteinDB",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "leader",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(einsteindb_raftstore_region_count{type=\"leader\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "region",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(einsteindb_raftstore_region_count{type=\"region\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{job=\"einsteindb\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(process_resident_memory_bytes{job=\"einsteindb\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "causetstore size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(einsteindb_engine_size_bytes) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "cf size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(einsteindb_engine_size_bytes) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "channel full",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_channel_full_total[1m])) by (instance, type)",
       "legendFormat": "{{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "server report failures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_server_report_failure_msg_total[1m])) by (type,instance,store_id)",
       "legendFormat": "{{instance}} - {{type}} - to - {{store_id}}"
      }
     ]
    },
    {
     "title": "scheduler pending commands",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(einsteindb_scheduler_contex_total) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "interlock executor count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_interlocking_directorate_executor_count[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "interlock  request duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_interlocking_directorate_request_duration_seconds_bucket[1m])) by (le,req))",
       "legendFormat": "{{req}}-99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_interlocking_directorate_request_duration_seconds_bucket[1m])) by (le,req))",
       "legendFormat": "{{req}}-95%"
      },
      {
       "expr": " sum(rate(einsteindb_interlocking_directorate_request_duration_seconds_sum{req=\"select\"}[1m])) /  sum(rate(einsteindb_interlocking_directorate_request_duration_seconds_count{req=\"select\"}[1m]))",
       "legendFormat": "select-avg"
      },
      {
       "expr": " sum(rate(einsteindb_interlocking_directorate_request_duration_seconds_sum{req=\"index\"}[1m])) /  sum(rate(einsteindb_interlocking_directorate_request_duration_seconds_count{req=\"index\"}[1m]))",
       "legendFormat": "index-avg"
      }
     ]
    },
    {
     "title": "raft causetstore CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{name=~\"raftstore_.*\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "interlocking_directorate CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{name=~\"INTERLOCK_.*\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Info",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vcores",
     "type": "block",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{mode=\"user\"}) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "block",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
     "targets": [
      { "expr": "node_memory_MemTotal_bytes", "legendFormat": "{{ instance }}" }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m]) ) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Load [1m]",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "node_load1", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Memory Available",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "{{ instance }}" }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{device!=\"lo\"}[5m])",
       "legendFormat": "Inbound:  {{instance}}"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\"}[5m])",
       "legendFormat": "Outbound:  {{instance}}"
      }
     ]
    },
    {
     "title": "TCP Retrans",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_RetransSegs[1m])",
       "legendFormat": "{{instance}} - TCPSlowStartRetrans"
      }
     ]
    },
    {
     "title": "IO Util",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total[1m])",
       "legendFormat": "{{instance}} - {{device}}"
      }
     ]
    }
   ]
  }
 ]
}