{
 "title": "Test-Cluster-MilevaDB",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Query Summary",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration",
     "type": "graph",
     "description": "MilevaDB query durations by histogram buckets with different percents",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "80"
      }
     ]
    },
    {
     "title": "Command Per Second",
     "type": "graph",
     "description": "MyALLEGROSQL commands processing numbers per second. See https://dev.allegrosql.com/doc/internals/en/text-protocol.html and https://dev.allegrosql.com/doc/internals/en/prepared-statements.html",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_server_query_total[1m])) by (result)",
       "legendFormat": "query {{result}}"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "description": "MilevaDB statement statistics",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_executor_statement_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(rate(milevadb_executor_statement_total[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "CPS By Instance",
     "type": "graph",
     "description": "MilevaDB command total statistics including both successful and failed ones",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(milevadb_server_query_total[1m])",
       "legendFormat": "{{instance}} {{type}} {{result}}"
      }
     ]
    },
    {
     "title": "Failed Query OPM",
     "type": "graph",
     "description": "MilevaDB failed query statistics by query type",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milevadb_server_execute_error_total[1m])) by (type, instance)",
       "legendFormat": " {{type}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Slow query",
     "type": "graph",
     "description": "MilevaDB slow query statistics with slow query durations and interlock waiting/executing durations",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(milevadb_server_slow_query_process_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "all_proc"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(milevadb_server_slow_query_INTERLOCK_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "all_INTERLOCK_proc"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(milevadb_server_slow_query_wait_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "all_INTERLOCK_wait"
      }
     ]
    },
    {
     "title": "999 Duration",
     "type": "graph",
     "description": "MilevaDB durations for different query types with 99.9 percent buckets",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le,sql_type))",
       "legendFormat": "{{sql_type}}"
      }
     ]
    },
    {
     "title": "99 Duration",
     "type": "graph",
     "description": "MilevaDB durations for different query types with 99 percent buckets",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le,sql_type))",
       "legendFormat": "{{sql_type}}"
      }
     ]
    },
    {
     "title": "95 Duration",
     "type": "graph",
     "description": "MilevaDB durations for different query types with 95 percent buckets",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le,sql_type))",
       "legendFormat": "{{sql_type}}"
      }
     ]
    },
    {
     "title": "80 Duration",
     "type": "graph",
     "description": "MilevaDB durations for different query types with 80 percent buckets",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le,sql_type))",
       "legendFormat": "{{sql_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Detail",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration 80 By Instance",
     "type": "graph",
     "description": "MilevaDB durations with 80 percent buckets by instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Duration 95 By Instance",
     "type": "graph",
     "description": "MilevaDB durations with 95 percent buckets by instance",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Duration 99 By Instance",
     "type": "graph",
     "description": "MilevaDB durations with 99 percent buckets by instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Duration 999 By Instance",
     "type": "graph",
     "description": "MilevaDB durations with 99.9 percent buckets by instance",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Failed Query OPM Detail",
     "type": "graph",
     "description": "MilevaDB failed query statistics with failing infomation ",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(milevadb_server_execute_error_total[1m])",
       "legendFormat": "{{type}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Internal ALLEGROALLEGROSQL OPS",
     "type": "graph",
     "description": "The internal ALLEGROALLEGROSQL is used by MilevaDB itself.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_stochastik_restricted_sql_total[30s]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Server",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "graph",
     "description": "MilevaDB uptime since last restart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "(time() - process_start_time_seconds{job=\"milevadb\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "MilevaDB process rss memory usage. MilevaDB heap memory size in use ",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"milevadb\"}",
       "legendFormat": "process-{{instance}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"milevadb\"}",
       "legendFormat": "HeapInuse-{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "MilevaDB cpu usage calculated with process cpu running seconds",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"milevadb\"}[30s])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "milevadb_server_maxprocs{job=\"milevadb\"}",
       "legendFormat": "limit-{{instance}}"
      }
     ]
    },
    {
     "title": "Connection Count",
     "type": "graph",
     "description": "MilevaDB current connection counts",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "milevadb_server_connections", "legendFormat": "{{instance}}" },
      {
       "expr": "sum(milevadb_server_connections)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Open FD Count",
     "type": "graph",
     "description": "MilevaDB process opened file descriptors count",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{job=\"milevadb\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disconnection Count",
     "type": "graph",
     "description": "MilevaDB connection disconnected counts",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milevadb_server_disconnection_total) by (instance, result)",
       "legendFormat": "{{instance}}-{{result}}"
      }
     ]
    },
    {
     "title": "Goroutine Count",
     "type": "graph",
     "description": "MilevaDB process current goroutines count",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " go_goroutines{job=~\"milevadb.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Events OPM",
     "type": "graph",
     "description": "MilevaDB Server critical events total, including start/close/shutdown/hang etc",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(milevadb_server_event_total[10m])",
       "legendFormat": "{{instance}}-server {{type}}"
      }
     ]
    },
    {
     "title": "Prepare Statement Count",
     "type": "graph",
     "description": "MilevaDB instance prepare statements count",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "milevadb_server_prepared_stmts", "legendFormat": "{{instance}}" },
      {
       "expr": "sum(milevadb_server_prepared_stmts)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Keep Alive OPM",
     "type": "graph",
     "description": "MilevaDB instance monitor average keep alive times",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milevadb_monitor_keep_alive_total[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Panic And Critial Error",
     "type": "graph",
     "description": "MilevaDB instance critical errors count including panic etc",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(milevadb_server_panic_total[1m])",
       "legendFormat": "panic-{{instance}}"
      },
      {
       "expr": "increase(milevadb_server_critical_error_total[1m])",
       "legendFormat": "critical-{{instance}}"
      }
     ]
    },
    {
     "title": "Time Jump Back OPS",
     "type": "graph",
     "description": "MilevaDB monitor time jump back count",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milevadb_monitor_time_jump_back_total[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Get Token Duration",
     "type": "graph",
     "description": "Duration (us) for getting token, it should be small until concurrency limit is reached.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_server_get_token_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "Skip Binlog Count",
     "type": "graph",
     "description": "MilevaDB instance critical errors count including panic etc",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "milevadb_server_critical_error_total",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Client Data Traffic",
     "type": "graph",
     "description": "Data traffic statistics between MilevaDB and the client.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(milevadb_server_packet_io_bytes_sum[1m])",
       "legendFormat": "{{instance}}-{{type}}-rate"
      },
      {
       "expr": "milevadb_server_packet_io_bytes_sum",
       "legendFormat": "{{instance}}-{{type}}-total"
      }
     ]
    },
    {
     "title": "Handshake Error OPS",
     "type": "graph",
     "description": "MilevaDB processing handshake error count",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milevadb_server_handshake_error_total[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction OPS",
     "type": "graph",
     "description": "MilevaDB transaction processing counts by type and source.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_stochastik_transaction_duration_seconds_count[1m])) by (type, txn_mode)",
       "legendFormat": "{{type}}-{{txn_mode}}"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "Bucketed histogram of transaction execution durations, including retry",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_stochastik_transaction_duration_seconds_bucket[1m])) by (le, txn_mode))",
       "legendFormat": "99-{{txn_mode}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_stochastik_transaction_duration_seconds_bucket[1m])) by (le, txn_mode))",
       "legendFormat": "95-{{txn_mode}}"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_stochastik_transaction_duration_seconds_bucket[1m])) by (le, txn_mode))",
       "legendFormat": "80-{{txn_mode}}"
      }
     ]
    },
    {
     "title": "Transaction Statement Num",
     "type": "heatmap",
     "description": "MilevaDB statements numbers within one transaction.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "targets": [
      {
       "expr": "sum(increase(milevadb_stochastik_transaction_statement_num_bucket[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Transaction Retry Num",
     "type": "heatmap",
     "description": "MilevaDB transaction retry histogram bucket statistics",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(increase(milevadb_stochastik_retry_num_bucket[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Stochastik Retry Error OPS",
     "type": "graph",
     "description": "Error numbers of transaction retry",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_stochastik_retry_error_total[30s])) by (type, sql_type)",
       "legendFormat": "{{type}}-{{sql_type}}"
      }
     ]
    },
    {
     "title": "Commit Token Wait Duration",
     "type": "graph",
     "description": "The duration of a transaction waits for a token when committing.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_einsteindbclient_batch_executor_token_wait_duration_bucket[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_einsteindbclient_batch_executor_token_wait_duration_bucket[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_einsteindbclient_batch_executor_token_wait_duration_bucket[1m])) by (le))",
       "legendFormat": "80"
      }
     ]
    },
    {
     "title": "KV Transaction OPS",
     "type": "graph",
     "description": "MilevaDB total ekv transaction counts",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_txn_cmd_duration_seconds_count[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "KV Transaction Duration",
     "type": "graph",
     "description": "The duration of the transaction commit/rollback on EinsteinDB.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_einsteindbclient_txn_cmd_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "99-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_einsteindbclient_txn_cmd_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "95-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_einsteindbclient_txn_cmd_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "80-{{type}}"
      }
     ]
    },
    {
     "title": "Transaction Regions Num",
     "type": "heatmap",
     "description": "regions transaction operates on count",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(milevadb_einsteindbclient_txn_regions_num_bucket[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Transaction Write KV Num Rate and Sum",
     "type": "graph",
     "description": "ekv write times per transaction execution",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(milevadb_einsteindbclient_txn_write_kv_num_sum[30s])",
       "legendFormat": "{{instance}}-rate"
      },
      {
       "expr": "milevadb_einsteindbclient_txn_write_kv_num_sum",
       "legendFormat": "{{instance}}-sum"
      }
     ]
    },
    {
     "title": "Transaction Write KV Num",
     "type": "heatmap",
     "description": "ekv write times per transaction execution",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "targets": [
      {
       "expr": "sum(increase(milevadb_einsteindbclient_txn_write_kv_num_bucket[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Statement Lock Keys",
     "type": "heatmap",
     "description": "The number of statement acquires locks.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "targets": [
      {
       "expr": "sum(increase(milevadb_stochastik_statement_lock_keys_count_bucket[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Send HeartBeat Duration",
     "type": "graph",
     "description": "When the pessimistic transaction begins to work, it will send heartbeat requests to uFIDelate its TTL. \nThis metric is the latency of the send heartbeat operation.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_einsteindbclient_txn_heart_beat_bucket[1m])) by (le, type))",
       "legendFormat": "80-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_einsteindbclient_txn_heart_beat_bucket[1m])) by (le, type))",
       "legendFormat": "95-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_einsteindbclient_txn_heart_beat_bucket[1m])) by (le, type))",
       "legendFormat": "99-{{type}}"
      }
     ]
    },
    {
     "title": "Transaction Write Size Bytes Rate and Sum",
     "type": "graph",
     "description": "ekv write size per transaction execution",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(milevadb_einsteindbclient_txn_write_size_bytes_sum[30s])",
       "legendFormat": "{{instance}}-rate"
      },
      {
       "expr": "milevadb_einsteindbclient_txn_write_size_bytes_sum",
       "legendFormat": "{{instance}}-sum"
      }
     ]
    },
    {
     "title": "Transaction Write Size Bytes",
     "type": "heatmap",
     "description": "ekv write size per transaction execution",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
     "targets": [
      {
       "expr": "sum(increase(milevadb_einsteindbclient_txn_write_size_bytes_bucket[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Acquire Pessimistic Locks Duration",
     "type": "graph",
     "description": "The duration of a statement acquiring all pessimistic locks at a time.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_einsteindbclient_pessimistic_lock_keys_duration_bucket[1m])) by (le))",
       "legendFormat": "80"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_einsteindbclient_pessimistic_lock_keys_duration_bucket[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_einsteindbclient_pessimistic_lock_keys_duration_bucket[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "TTL Lifetime Reach Counter",
     "type": "graph",
     "description": "This metric means the pessimistic lives too long which is abnormal.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_ttl_lifetime_reach_total[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Load Safepoint OPS",
     "type": "graph",
     "description": "safe point loading times",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_load_safepoint_total{type=\"ok\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Pessimistic Statement Retry OPS",
     "type": "heatmap",
     "description": "When the pessimistic statement is executed, the dagger fails and it can retry automatically. The number of times the statement is retried is recorded.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum(increase(milevadb_stochastik_statement_pessimistic_retry_count_bucket[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Executor",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Parse Duration",
     "type": "graph",
     "description": "The time cost of parsing ALLEGROALLEGROSQL to AST",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_stochastik_parse_duration_seconds_bucket[1m])) by (le, sql_type))",
       "legendFormat": "{{sql_type}}"
      }
     ]
    },
    {
     "title": "Compile Duration",
     "type": "graph",
     "description": "The time cost of building the query plan",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_stochastik_compile_duration_seconds_bucket[1m])) by (le, sql_type))",
       "legendFormat": "{{sql_type}}"
      }
     ]
    },
    {
     "title": "Execution Duration",
     "type": "graph",
     "description": "The time cost of executing the ALLEGROALLEGROSQL which does not include the time to get the results of the query .",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_stochastik_execute_duration_seconds_bucket[1m])) by (le, sql_type))",
       "legendFormat": "{{sql_type}}"
      }
     ]
    },
    {
     "title": "Expensive Executors OPS",
     "type": "graph",
     "description": "MilevaDB executors using more cpu and memory resources",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_executor_expensive_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Queries Using Plan Cache OPS",
     "type": "graph",
     "description": "MilevaDB plan cache hit total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_server_plan_cache_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distsql",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distsql Duration",
     "type": "graph",
     "description": "durations of distsql execution by type",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 122 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(milevadb_distsql_handle_query_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "999-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_distsql_handle_query_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "99-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(milevadb_distsql_handle_query_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "90-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(milevadb_distsql_handle_query_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "50-{{type}}"
      }
     ]
    },
    {
     "title": "Distsql QPS",
     "type": "graph",
     "description": "distsql query handling durations per second",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 122 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_distsql_handle_query_duration_seconds_count[1m]))"
      }
     ]
    },
    {
     "title": "Distsql Partial QPS",
     "type": "graph",
     "description": "the numebr of distsql partial scan numbers",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 129 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_distsql_scan_keys_partial_num_count[1m]))"
      }
     ]
    },
    {
     "title": "Scan Keys Num",
     "type": "graph",
     "description": "the numebr of distsql scan numbers",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 129 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(milevadb_distsql_scan_keys_num_bucket[1m])) by (le))",
       "legendFormat": "100"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(milevadb_distsql_scan_keys_num_bucket[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(milevadb_distsql_scan_keys_num_bucket[1m])) by (le))",
       "legendFormat": "50"
      }
     ]
    },
    {
     "title": "Scan Keys Partial Num",
     "type": "graph",
     "description": "the numebr of distsql partial scan key numbers",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 129 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(milevadb_distsql_scan_keys_partial_num_bucket[1m])) by (le))",
       "legendFormat": "100"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(milevadb_distsql_scan_keys_partial_num_bucket[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_distsql_scan_keys_partial_num_bucket[1m])) by (le))",
       "legendFormat": "50"
      }
     ]
    },
    {
     "title": "Partial Num",
     "type": "graph",
     "description": "distsql partial numbers per query",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 136 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(milevadb_distsql_partial_num_bucket[1m])) by (le))",
       "legendFormat": "100"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(milevadb_distsql_partial_num_bucket[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(milevadb_distsql_partial_num_bucket[1m])) by (le))",
       "legendFormat": "50"
      }
     ]
    },
    {
     "title": "interlocking_directorate Seconds 999",
     "type": "graph",
     "description": "ekv storage interlock processing durations",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 136 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(milevadb_einsteindbclient_INTERLOCK_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "KV Errors",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Backoff Duration",
     "type": "graph",
     "description": "ekv backoff time durations by type",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(milevadb_einsteindbclient_backoff_seconds_bucket[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_einsteindbclient_backoff_seconds_bucket[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_einsteindbclient_backoff_seconds_bucket[1m])) by (le))",
       "legendFormat": "80"
      }
     ]
    },
    {
     "title": "TiClient Region Error OPS",
     "type": "graph",
     "description": "ekv region error times",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_region_err_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Backoff OPS",
     "type": "graph",
     "description": "ekv storage backoff times",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_backoff_seconds_count[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Lock Resolve OPS",
     "type": "graph",
     "description": "dagger resolve times",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_lock_resolver_actions_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Other Errors OPS",
     "type": "graph",
     "description": "dagger cleanup failed times and safe point uFIDelate times",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_lock_cleanup_task_total[1m])) by (type)",
       "legendFormat": "cleanup_secondary_failure_{{type}}"
      },
      {
       "expr": "sum(rate(milevadb_einsteindbclient_load_safepoint_total{type=\"fail\"}[1m]))",
       "legendFormat": "load_safepoint_failure"
      }
     ]
    }
   ]
  },
  {
   "title": "KV Request",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Request OPS",
     "type": "graph",
     "description": "ekv request total by instance and command type",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_request_seconds_count[1m])) by (instance, type)",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "KV Request Duration 99 by causetstore",
     "type": "graph",
     "description": "ekv requests durations by causetstore",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_einsteindbclient_request_seconds_bucket{type!=\"GC\"}[1m])) by (le, causetstore))",
       "legendFormat": "causetstore-{{causetstore}}"
      }
     ]
    },
    {
     "title": "KV Request Duration 99 by type",
     "type": "graph",
     "description": "ekv request durations by request type",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_einsteindbclient_request_seconds_bucket{type!=\"GC\"}[1m])) by (le,type))",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FIDel Client",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "FIDel Client CMD OPS",
     "type": "graph",
     "description": "fidel command count by type",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(FIDel_client_cmd_handle_cmds_duration_seconds_count{type!=\"tso\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "FIDel Client CMD Duration",
     "type": "graph",
     "description": "fidel client command durations by type within 99.9 percent buckets",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(FIDel_client_cmd_handle_cmds_duration_seconds_bucket{type!~\"tso|tso_async_wait\"}[1m])) by (le, type))",
       "legendFormat": "999-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(FIDel_client_cmd_handle_cmds_duration_seconds_bucket{type!~\"tso|tso_async_wait\"}[1m])) by (le, type))",
       "legendFormat": "99-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(FIDel_client_cmd_handle_cmds_duration_seconds_bucket{type!~\"tso|tso_async_wait\"}[1m])) by (le, type))",
       "legendFormat": "90-{{type}}"
      }
     ]
    },
    {
     "title": "FIDel Client CMD Fail OPS",
     "type": "graph",
     "description": "fidel client command fail count by type",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(FIDel_client_cmd_handle_failed_cmds_duration_seconds_count[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "FIDel TSO OPS",
     "type": "graph",
     "description": "The duration of a client calling GetTSAsync until received the TS result.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(FIDel_client_cmd_handle_cmds_duration_seconds_count{type=\"tso\"}[1m]))",
       "legendFormat": "cmd"
      },
      {
       "expr": "sum(rate(FIDel_client_request_handle_requests_duration_seconds_count{type=\"tso\"}[1m]))",
       "legendFormat": "request"
      }
     ]
    },
    {
     "title": "FIDel TSO Wait Duration",
     "type": "graph",
     "description": "The duration of a client starting to wait for the TS until received the TS result.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(FIDel_client_cmd_handle_cmds_duration_seconds_bucket{type=\"wait\"}[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(FIDel_client_cmd_handle_cmds_duration_seconds_bucket{type=\"wait\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(FIDel_client_cmd_handle_cmds_duration_seconds_bucket{type=\"wait\"}[1m])) by (le))",
       "legendFormat": "90"
      }
     ]
    },
    {
     "title": "FIDel TSO RPC Duration",
     "type": "graph",
     "description": "The duration of a client sending TSO request until received the response.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(FIDel_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(FIDel_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(FIDel_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "90"
      }
     ]
    },
    {
     "title": "Start TSO Wait Duration",
     "type": "graph",
     "description": "The duration of the waiting time for getting the start timestamp oracle",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(milevadb_FIDelclient_ts_future_wait_seconds_bucket[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_FIDelclient_ts_future_wait_seconds_bucket[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(milevadb_FIDelclient_ts_future_wait_seconds_bucket[1m])) by (le))",
       "legendFormat": "90"
      }
     ]
    }
   ]
  },
  {
   "title": "Schema Load",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Schema Duration",
     "type": "graph",
     "description": "MilevaDB loading schemaReplicant time durations by instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_petri_load_schema_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Load Schema OPS",
     "type": "graph",
     "description": "MilevaDB loading schemaReplicant times including both failed and successful ones",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_petri_load_schema_total[1m])) by (instance,type)",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "Schema Lease Error OPM",
     "type": "graph",
     "description": "MilevaDB schemaReplicant lease error counts",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milevadb_stochastik_schema_lease_error_total[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Load Privilege OPS",
     "type": "graph",
     "description": "MilevaDB load privilege counts",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_petri_load_privilege_total[1m])) by (instance,type)",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DBS",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "DBS Duration 95",
     "type": "graph",
     "description": "MilevaDB DBS duration statistics",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_dbs_handle_job_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Batch Add Index Duration 100",
     "type": "graph",
     "description": "MilevaDB batch add index durations by histogram buckets",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(milevadb_dbs_batch_add_idx_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(rate(milevadb_dbs_add_index_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "DBS Waiting Jobs Count",
     "type": "graph",
     "description": "MilevaDB dbs request in queue",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "milevadb_dbs_waiting_jobs", "legendFormat": "{{instance}}-{{type}}" }
     ]
    },
    {
     "title": "DBS META OPM",
     "type": "graph",
     "description": "MilevaDB different dbs worker numbers",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(milevadb_dbs_worker_operation_total[1m])",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "DBS Worker Duration 99",
     "type": "graph",
     "description": "MilevaDB worker duration by type, action, results",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(increase(milevadb_dbs_worker_operation_duration_seconds_bucket[1m])) by (le, type, action, result))",
       "legendFormat": "{{type}}-{{action}}-{{result}}"
      }
     ]
    },
    {
     "title": "Deploy Syncer Duration",
     "type": "graph",
     "description": "MilevaDB dbs schemaReplicant syncer statistics, including init, start, watch, clear function call time cost",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(milevadb_dbs_deploy_syncer_duration_seconds_bucket[2m])) by (le, type, result))",
       "legendFormat": "{{type}}-{{result}}"
      }
     ]
    },
    {
     "title": "Owner Handle Syncer Duration",
     "type": "graph",
     "description": "MilevaDB dbs owner time operations on etcd duration statistics ",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(milevadb_dbs_owner_handle_syncer_duration_seconds_bucket[2m])) by (le, type, result))",
       "legendFormat": "{{type}}-{{result}}"
      }
     ]
    },
    {
     "title": "UFIDelate Self Version Duration",
     "type": "graph",
     "description": "MilevaDB schemaReplicant syncer version uFIDelate time duration",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(milevadb_dbs_uFIDelate_self_ver_duration_seconds_bucket[2m])) by (le, result))",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "DBS OPM",
     "type": "graph",
     "description": "executed DBS jobs per minute",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_dbs_handle_job_duration_seconds_count[1m])) by (type)",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "sum(rate(milevadb_dbs_handle_job_duration_seconds_count[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "DBS add index progress in percentage",
     "type": "graph",
     "description": "MilevaDB DBS add index progress in percentage. The value is [0,100]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "milevadb_dbs_add_index_percentage_progress",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auto Analyze Duration 95",
     "type": "graph",
     "description": "MilevaDB auto analyze time durations within 95 percent histogram buckets",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 149 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_statistics_auto_analyze_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "auto analyze duration"
      }
     ]
    },
    {
     "title": "Auto Analyze QPS",
     "type": "graph",
     "description": "MilevaDB auto analyze query per second",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 149 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_statistics_auto_analyze_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Stats Inaccuracy Rate",
     "type": "graph",
     "description": "MilevaDB statistics inaccurate rate",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 149 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_statistics_stats_inaccuracy_rate_bucket[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(milevadb_statistics_stats_inaccuracy_rate_bucket[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(milevadb_statistics_stats_inaccuracy_rate_bucket[1m])) by (le))",
       "legendFormat": "50"
      }
     ]
    },
    {
     "title": "Pseudo Estimation OPS",
     "type": "graph",
     "description": "MilevaDB optimizer using pseudo estimation counts",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 156 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_statistics_pseudo_estimation_total[1m]))",
       "legendFormat": "Pseudo OPS"
      }
     ]
    },
    {
     "title": "Dump Feedback OPS",
     "type": "graph",
     "description": "MilevaDB dumping statistics back to ekv storage times",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 156 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_statistics_dump_feedback_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "CausetStore Query Feedback QPS",
     "type": "graph",
     "description": "MilevaDB causetstore quering feedback counts",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 156 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_statistics_store_query_feedback_total[1m])) by (type) ",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Significant Feedback",
     "type": "graph",
     "description": "Counter of query feedback whose actual count is much different than calculated by current statistics",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 163 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_statistics_high_error_rate_feedback_total[1m]))",
       "legendFormat": "Significant Feedback"
      }
     ]
    },
    {
     "title": "UFIDelate Stats OPS",
     "type": "graph",
     "description": "MilevaDB uFIDelating statistics using feed back counts",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 163 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_statistics_uFIDelate_stats_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Fast Analyze Status 100",
     "type": "graph",
     "description": "MilevaDB fast analyze statistics ",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 163 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(milevadb_statistics_fast_analyze_status_bucket[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Owner",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "New ETCD Stochastik Duration 95",
     "type": "graph",
     "description": "MilevaDB new stochastik durations for new etcd stochastik",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 150 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_owner_new_stochastik_duration_seconds_bucket[1m])) by (le, instance, result))",
       "legendFormat": "{{instance}}-{{result}}"
      }
     ]
    },
    {
     "title": "Owner Watcher OPS",
     "type": "graph",
     "description": "MilevaDB owner  watcher counts",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 150 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_owner_watch_owner_total[1m])) by (type, result, instance)",
       "legendFormat": "{{type}}-{{result}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Owner Watcher OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 150 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_owner_watch_owner_total[1m])) by (type, result, instance)",
       "legendFormat": "{{type}}-{{result}}-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Meta",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "AutoID QPS",
     "type": "graph",
     "description": "MilevaDB auto id requests per second including  single block/global auto id processing and single block auto id rebase processing",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_autoid_operation_duration_seconds_count[1m]))",
       "legendFormat": "AutoID QPS"
      }
     ]
    },
    {
     "title": "AutoID Duration",
     "type": "graph",
     "description": "MilevaDB auto id requests durations",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_autoid_operation_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "99-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_autoid_operation_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "80-{{type}}"
      }
     ]
    },
    {
     "title": "Region Cache Error OPS",
     "type": "graph",
     "description": "MilevaDB region cache operations count",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_region_cache_operations_total{result=\"err\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Meta Operations Duration 99",
     "type": "graph",
     "description": "MilevaDB meta operation durations including get/set schemaReplicant and dbs jobs",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_meta_operation_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker CausetAction OPM",
     "type": "graph",
     "description": "ekv storage garbage collection counts by type",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milevadb_einsteindbclient_gc_worker_actions_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Duration 99",
     "type": "graph",
     "description": "ekv storage garbage collection time durations",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_einsteindbclient_gc_seconds_bucket[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "Config",
     "type": "graph",
     "description": "ekv storage garbage collection config including gc_life_time and gc_run_interval",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(milevadb_einsteindbclient_gc_config) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "GC Failure OPM",
     "type": "graph",
     "description": "ekv storage garbage collection failing counts",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milevadb_einsteindbclient_gc_failure[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Delete Range Failure OPM",
     "type": "graph",
     "description": "ekv storage unsafe destroy range failed counts",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milevadb_einsteindbclient_gc_unsafe_destroy_range_failures[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Too Many Locks Error OPM",
     "type": "graph",
     "description": "ekv storage region garbage collection clean too many locks count",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milevadb_einsteindbclient_gc_region_too_many_locks[1m]))",
       "legendFormat": "Locks Error OPM"
      }
     ]
    },
    {
     "title": "CausetAction Result OPM",
     "type": "graph",
     "description": "ekv storage garbage collection results including failed and successful ones",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milevadb_einsteindbclient_gc_action_result[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Delete Range Task Status",
     "type": "graph",
     "description": "ekv storage delete range task execution status by type",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milevadb_einsteindbclient_range_task_stats) by (type, result)",
       "legendFormat": "{{type}}-{{result}}"
      }
     ]
    },
    {
     "title": "Push Task Duration 95",
     "type": "graph",
     "description": "ekv storage range worker processing one task duration",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_einsteindbclient_range_task_push_duration_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Batch Client",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending Request Count by EinsteinDB",
     "type": "graph",
     "description": "ekv storage batch requests in queue",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milevadb_einsteindbclient_pending_batch_requests) by (causetstore)",
       "legendFormat": "{{causetstore}}"
      }
     ]
    },
    {
     "title": "Wait Duration 95",
     "type": "graph",
     "description": "ekv storage batch processing durations",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_einsteindbclient_batch_wait_duration_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Wait Connection Establish Duration",
     "type": "graph",
     "description": "ekv storage batch client wait new connection establish duration",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9999, sum(rate(milevadb_einsteindbclient_batch_client_wait_connection_establish_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "No Available Connection Counter",
     "type": "graph",
     "description": "Metrics for 'no available connection'.\nThere should be no data here if the connection between MilevaDB and EinsteinDB is healthy.",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "milevadb_einsteindbclient_batch_client_no_available_connection_total",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Batch Client Unavailable Duration 95",
     "type": "graph",
     "description": "ekv storage batch processing unvailable durations",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_einsteindbclient_batch_client_unavailable_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}