{
 "title": "Test-Cluster-MilevaDB-Runtime",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(process_start_time_seconds{job=\"milevadb\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "$instance",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "MilevaDB process rss memory usage. MilevaDB heap memory size in use ",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "alloc-from-os"
      },
      {
       "expr": "go_memstats_next_gc_bytes{instance=~\"$instance\"} / 2",
       "legendFormat": "estimate-inuse"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"} - go_memstats_next_gc_bytes{instance=~\"$instance\"} / 2",
       "legendFormat": "estimate-garbage"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{instance=~\"$instance\"} - go_memstats_heap_released_bytes{instance=~\"$instance\"} + go_memstats_heap_inuse_bytes{instance=~\"$instance\"} - go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
       "legendFormat": "reserved-by-go"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{instance=~\"$instance\"} + go_memstats_mspan_sys_bytes{instance=~\"$instance\"} + go_memstats_mcache_sys_bytes{instance=~\"$instance\"} + go_memstats_buck_hash_sys_bytes{instance=~\"$instance\"} + go_memstats_gc_sys_bytes{instance=~\"$instance\"} + go_memstats_other_sys_bytes{instance=~\"$instance\"}",
       "legendFormat": "used-by-go"
      },
      {
       "expr": "go_memstats_next_gc_bytes{instance=~\"$instance\"}",
       "legendFormat": "gc-threshold"
      },
      {
       "expr": "(clamp_max(idelta(go_memstats_last_gc_time_seconds{instance=~\"$instance\"}[1m]), 1) * go_memstats_next_gc_bytes{instance=~\"$instance\"}) > 0",
       "legendFormat": "gc"
      }
     ]
    },
    {
     "title": "Estimated Live Objects",
     "type": "graph",
     "description": "Count of live objects.",
     "gridPos": { "x": 12, "y": 1, "w": 12, "h": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_objects{instance=~\"$instance\"}",
       "legendFormat": "objects"
      }
     ]
    },
    {
     "title": "GC STW Duration (last 256 GC cycles)",
     "type": "graph",
     "description": "MilevaDB process Go garbage collection STW pause duration",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{instance=~\"$instance\", quantile=\"0\"}",
       "legendFormat": "min"
      },
      {
       "expr": "go_gc_duration_seconds{instance=~\"$instance\", quantile!~\"0|1\"}",
       "legendFormat": "{{quantile}}"
      },
      {
       "expr": "go_gc_duration_seconds{instance=~\"$instance\", quantile=\"1\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "MilevaDB cpu usage calculated with process cpu running seconds",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{instance=~\"$instance\"}[30s])",
       "legendFormat": "cpu-usage"
      },
      {
       "expr": "milevadb_server_maxprocs{instance=~\"$instance\"}",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "GC CPU Time",
     "type": "graph",
     "description": "The CPU time (aggregated) used by grabage collector.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(idelta((go_memstats_gc_cpu_fraction{instance=~\"$instance\"} * (go_memstats_last_gc_time_seconds{instance=~\"$instance\"} - process_start_time_seconds{instance=~\"$instance\"}) * milevadb_server_maxprocs{instance=~\"$instance\"})[30s:]) / idelta(go_gc_duration_seconds_count{instance=~\"$instance\"}[30s])) > 0",
       "legendFormat": "cpu-time"
      }
     ]
    },
    {
     "title": "Goroutine Count",
     "type": "graph",
     "description": "MilevaDB process current goroutines count",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " go_goroutines{instance=~\"$instance\"}",
       "legendFormat": "goroutines"
      },
      {
       "expr": "go_threads{instance=~\"$instance\"}",
       "legendFormat": "threads"
      }
     ]
    },
    {
     "title": "SlabPredictor Throughput",
     "type": "graph",
     "description": "The throughput of Go's memory allocator.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(go_memstats_alloc_bytes_total{instance=~\"$instance\"}[30s])",
       "legendFormat": "alloc"
      },
      {
       "expr": "irate((go_memstats_alloc_bytes_total{instance=~\"$instance\"} - go_memstats_heap_alloc_bytes{instance=~\"$instance\"})[30s:])",
       "legendFormat": "sweep"
      },
      {
       "expr": "irate(go_memstats_mallocs_total{instance=~\"$instance\"}[30s])",
       "legendFormat": "alloc-ops"
      },
      {
       "expr": "irate(go_memstats_frees_total{instance=~\"$instance\"}[30s])",
       "legendFormat": "swepp-ops"
      }
     ]
    },
    {
     "title": "TSO RPC Latency",
     "type": "graph",
     "description": "MilevaDB side and FIDel side TSO RPC duration.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(FIDel_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[30s])) by (le))",
       "legendFormat": "milevadb-side"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(FIDel_server_handle_tso_duration_seconds_bucket[30s])) by (le))",
       "legendFormat": "fidel-side"
      }
     ]
    },
    {
     "title": "GC Count (in the last 15s)",
     "type": "graph",
     "description": "The Go garbage collection counts in the last 15s",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "idelta(go_gc_duration_seconds_count{instance=~\"$instance\"}[30s]) > 0",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "KV RPC Latency",
     "type": "graph",
     "description": "MilevaDB side and EinsteinDB side RPC duration.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_einsteindbclient_request_seconds_bucket{type!=\"GC\",instance=~\"$instance\"}[30s])) by (le, causetstore))",
       "legendFormat": "milevadb-to-causetstore{{causetstore}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_grpc_msg_duration_seconds_bucket{type!=\"kv_gc\"}[30s])) by (le, instance))",
       "legendFormat": "einsteindb-{{instance}}-side"
      }
     ]
    }
   ]
  }
 ]
}