package causetnet

import (
	"context"
	"crypto/tls"
	"encoding/json"
	"fmt"
	"net"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/ngaut/pools"
	"github.com/opentracing/opentracing-go"
	"github.com/whtcorpsinc/MilevaDB-Prod/BerolinaSQL"
	"github.com/whtcorpsinc/MilevaDB-Prod/BerolinaSQL/ast"
	"github.com/whtcorpsinc/MilevaDB-Prod/BerolinaSQL/auth"
	"github.com/whtcorpsinc/MilevaDB-Prod/BerolinaSQL/charset"
	"github.com/whtcorpsinc/MilevaDB-Prod/BerolinaSQL/mysql"
	"github.com/whtcorpsinc/MilevaDB-Prod/BerolinaSQL/serial"
	"github.com/whtcorpsinc/MilevaDB-Prod/BerolinaSQL/terror"
	"github.com/whtcorpsinc/MilevaDB-Prod/Interlock"
	"github.com/whtcorpsinc/MilevaDB-Prod/bindinfo"
	"github.com/whtcorpsinc/MilevaDB-Prod/causetnetctx"
	"github.com/whtcorpsinc/MilevaDB-Prod/causetnetctx/binloginfo"
	"github.com/whtcorpsinc/MilevaDB-Prod/causetnetctx/stmtctx"
	"github.com/whtcorpsinc/MilevaDB-Prod/causetnetctx/variable"
	"github.com/whtcorpsinc/MilevaDB-Prod/config"
	"github.com/whtcorpsinc/MilevaDB-Prod/ekv"
	"github.com/whtcorpsinc/MilevaDB-Prod/meta"
	"github.com/whtcorpsinc/MilevaDB-Prod/metrics"
	"github.com/whtcorpsinc/MilevaDB-Prod/owner"
	"github.com/whtcorpsinc/MilevaDB-Prod/planner"
	plannercore "github.com/whtcorpsinc/MilevaDB-Prod/planner/core"
	"github.com/whtcorpsinc/MilevaDB-Prod/plugin"
	"github.com/whtcorpsinc/MilevaDB-Prod/privilege"
	"github.com/whtcorpsinc/MilevaDB-Prod/privilege/privileges"
	"github.com/whtcorpsinc/MilevaDB-Prod/schemareplicant"
	"github.com/whtcorpsinc/MilevaDB-Prod/statistics/handle"
	"github.com/whtcorpsinc/MilevaDB-Prod/store/einsteindb"
	"github.com/whtcorpsinc/MilevaDB-Prod/types"
	"github.com/whtcorpsinc/MilevaDB-Prod/util"
	"github.com/whtcorpsinc/MilevaDB-Prod/util/chunk"
	"github.com/whtcorpsinc/MilevaDB-Prod/util/collate"
	"github.com/whtcorpsinc/MilevaDB-Prod/util/execdetails"
	"github.com/whtcorpsinc/MilevaDB-Prod/util/kvcache"
	"github.com/whtcorpsinc/MilevaDB-Prod/util/logutil"
	"github.com/whtcorpsinc/MilevaDB-Prod/util/sqlexec"
	"github.com/whtcorpsinc/MilevaDB-Prod/util/timeutil"
	"github.com/whtcorpsinc/ares_centroid_error"
	"github.com/whtcorpsinc/errors"
	"github.com/whtcorpsinc/noether/go-binlog"
	"go.uber.org/zap"
)

var (
	statementPerTransactionPessimisticOK    = metrics.StatementPerTransaction.WithLabelValues(metrics.LblPessimistic, metrics.LblOK)
	statementPerTransactionPessimisticError = metrics.StatementPerTransaction.WithLabelValues(metrics.LblPessimistic, metrics.LblError)
	statementPerTransactionOptimisticOK     = metrics.StatementPerTransaction.WithLabelValues(metrics.LblOptimistic, metrics.LblOK)
	statementPerTransactionOptimisticError  = metrics.StatementPerTransaction.WithLabelValues(metrics.LblOptimistic, metrics.LblError)
	transactionDurationPessimisticCommit    = metrics.TransactionDuration.WithLabelValues(metrics.LblPessimistic, metrics.LblCommit)
	transactionDurationPessimisticAbort     = metrics.TransactionDuration.WithLabelValues(metrics.LblPessimistic, metrics.LblAbort)
	transactionDurationOptimisticCommit     = metrics.TransactionDuration.WithLabelValues(metrics.LblOptimistic, metrics.LblCommit)
	transactionDurationOptimisticAbort      = metrics.TransactionDuration.WithLabelValues(metrics.LblOptimistic, metrics.LblAbort)

	causetnetExecuteCompileDurationInternal = metrics.CausetnetExecuteCompileDuration.WithLabelValues(metrics.LblInternal)
	causetnetExecuteCompileDurationGeneral  = metrics.CausetnetExecuteCompileDuration.WithLabelValues(metrics.LblGeneral)
	causetnetExecuteParseDurationInternal   = metrics.CausetnetExecuteParseDuration.WithLabelValues(metrics.LblInternal)
	causetnetExecuteParseDurationGeneral    = metrics.CausetnetExecuteParseDuration.WithLabelValues(metrics.LblGeneral)
)

// Causetnet context, it is consistent with the lifecycle of a client connection.
type Causetnet interface {
	causetnetctx.Context
	Status() uint16       // Flag of current status, such as autocommit.
	LastInsertID() uint64 // LastInsertID is the last inserted auto_increment ID.
	LastMessage() string  // LastMessage is the info message that may be generated by last command
	AffectedRows() uint64 // Affected rows by latest executed stmt.
	// Execute is deprecated, use ExecuteStmt() instead.
	Execute(context.Context, string) ([]sqlexec.RecordSet, error)         // Execute a sql statement.
	ExecuteInternal(context.Context, string) ([]sqlexec.RecordSet, error) // Execute a internal sql statement.
	ExecuteStmt(context.Context, ast.StmtNode) (sqlexec.RecordSet, error)
	Parse(ctx context.Context, sql string) ([]ast.StmtNode, error)
	String() string // String is used to debug.
	CommitTxn(context.Context) error
	RollbackTxn(context.Context)
	// PrepareStmt executes prepare statement in binary protocol.
	PrepareStmt(sql string) (stmtID uint32, paramCount int, fields []*ast.ResultField, err error)
	// ExecutePreparedStmt executes a prepared statement.
	ExecutePreparedStmt(ctx context.Context, stmtID uint32, param []types.CausetObjectQL) (sqlexec.RecordSet, error)
	DropPreparedStmt(stmtID uint32) error
	SetClientCapability(uint32) // Set client capability flags.
	SetConnectionID(uint64)
	SetCommandValue(byte)
	SetProcessInfo(string, time.Time, byte, uint64)
	SetTLSState(*tls.ConnectionState)
	SetCollation(coID int) error
	SetCausetnetManager(util.CausetnetManager)
	Close()
	Auth(user *auth.UserIdentity, auth []byte, salt []byte) bool
	ShowProcess() *util.ProcessInfo
	// PrepareTxnCtx is exported for test.
	PrepareTxnCtx(context.Context)
	// FieldList returns fields list of a table.
	FieldList(tableName string) (fields []*ast.ResultField, err error)
}

var (
	_ Causetnet = (*causetnet)(nil)
)

type stmtRecord struct {
	st      sqlexec.Statement
	stmtCtx *stmtctx.StatementContext
}

// StmtHistory holds all histories of statements in a txn.
type StmtHistory struct {
	history []*stmtRecord
}

// Add appends a stmt to history list.
func (h *StmtHistory) Add(st sqlexec.Statement, stmtCtx *stmtctx.StatementContext) {
	s := &stmtRecord{
		st:      st,
		stmtCtx: stmtCtx,
	}
	h.history = append(h.history, s)
}

// Count returns the count of the history.
func (h *StmtHistory) Count() int {
	return len(h.history)
}

type causetnet struct {
	// processInfo is used by ShowProcess(), and should be modified atomically.
	processInfo atomic.Value
	txn         TxnState

	mu struct {
		sync.RWMutex
		values map[fmt.Stringer]interface{}
	}

	currentPlan plannercore.Plan

	store ekv.Storage

	BerolinaSQL *BerolinaSQL.BerolinaSQL

	preparedPlanCache *kvcache.SimpleLRUCache

	causetnetVars    *variable.CausetnetVars
	causetnetManager util.CausetnetManager

	statsCollector *handle.CausetnetStatsCollector
	// ddlOwnerChecker is used in `select MilevaDB_is_ddl_owner()` statement;
	ddlOwnerChecker owner.DDLOwnerChecker
	// lockedTables use to record the table locks hold by the causetnet.
	lockedTables map[int64]serial.TableLockTpInfo

	// client shared interlocking_directorate client per causetnet
	client ekv.Client
}

// AddTableLock adds table dagger to the causetnet dagger map.
func (s *causetnet) AddTableLock(locks []serial.TableLockTpInfo) {
	for _, l := range locks {
		s.lockedTables[l.TableID] = l
	}
}

// ReleaseTableLocks releases table dagger in the causetnet dagger map.
func (s *causetnet) ReleaseTableLocks(locks []serial.TableLockTpInfo) {
	for _, l := range locks {
		delete(s.lockedTables, l.TableID)
	}
}

// ReleaseTableLockByTableIDs releases table dagger in the causetnet dagger map by table ID.
func (s *causetnet) ReleaseTableLockByTableIDs(tableIDs []int64) {
	for _, tblID := range tableIDs {
		delete(s.lockedTables, tblID)
	}
}

// CheckTableLocked checks the table dagger.
func (s *causetnet) CheckTableLocked(tblID int64) (bool, serial.TableLockType) {
	lt, ok := s.lockedTables[tblID]
	if !ok {
		return false, serial.TableLockNone
	}
	return true, lt.Tp
}

// GetAllTableLocks gets all table locks table id and db id hold by the causetnet.
func (s *causetnet) GetAllTableLocks() []serial.TableLockTpInfo {
	lockTpInfo := make([]serial.TableLockTpInfo, 0, len(s.lockedTables))
	for _, tl := range s.lockedTables {
		lockTpInfo = append(lockTpInfo, tl)
	}
	return lockTpInfo
}

// HasLockedTables uses to check whether this causetnet locked any blocks.
// If so, the causetnet can only visit the table which locked by self.
func (s *causetnet) HasLockedTables() bool {
	b := len(s.lockedTables) > 0
	return b
}

// ReleaseAllTableLocks releases all table locks hold by the causetnet.
func (s *causetnet) ReleaseAllTableLocks() {
	s.lockedTables = make(map[int64]serial.TableLockTpInfo)
}

// DDLOwnerChecker returns s.ddlOwnerChecker.
func (s *causetnet) DDLOwnerChecker() owner.DDLOwnerChecker {
	return s.ddlOwnerChecker
}

func (s *causetnet) cleanRetryInfo() {
	if s.causetnetVars.RetryInfo.Retrying {
		return
	}

	retryInfo := s.causetnetVars.RetryInfo
	defer retryInfo.Clean()
	if len(retryInfo.DroppedPreparedStmtIDs) == 0 {
		return
	}

	planCacheEnabled := plannercore.PreparedPlanCacheEnabled()
	var cacheKey kvcache.Key
	var preparedAst *ast.Prepared
	if planCacheEnabled {
		firstStmtID := retryInfo.DroppedPreparedStmtIDs[0]
		if preparedPointer, ok := s.causetnetVars.PreparedStmts[firstStmtID]; ok {
			preparedObj, ok := preparedPointer.(*plannercore.CachedPrepareStmt)
			if ok {
				preparedAst = preparedObj.PreparedAst
				cacheKey = plannercore.NewPSTMTPlanCacheKey(s.causetnetVars, firstStmtID, preparedAst.SchemaVersion)
			}
		}
	}
	for i, stmtID := range retryInfo.DroppedPreparedStmtIDs {
		if planCacheEnabled {
			if i > 0 && preparedAst != nil {
				plannercore.SetPstmtIDSchemaVersion(cacheKey, stmtID, preparedAst.SchemaVersion, s.causetnetVars.IsolationReadEngines)
			}
			s.PreparedPlanCache().Delete(cacheKey)
		}
		s.causetnetVars.RemovePreparedStmt(stmtID)
	}
}

func (s *causetnet) Status() uint16 {
	return s.causetnetVars.Status
}

func (s *causetnet) LastInsertID() uint64 {
	if s.causetnetVars.StmtCtx.LastInsertID > 0 {
		return s.causetnetVars.StmtCtx.LastInsertID
	}
	return s.causetnetVars.StmtCtx.InsertID
}

func (s *causetnet) LastMessage() string {
	return s.causetnetVars.StmtCtx.GetMessage()
}

func (s *causetnet) AffectedRows() uint64 {
	return s.causetnetVars.StmtCtx.AffectedRows()
}

func (s *causetnet) SetClientCapability(capability uint32) {
	s.causetnetVars.ClientCapability = capability
}

func (s *causetnet) SetConnectionID(connectionID uint64) {
	s.causetnetVars.ConnectionID = connectionID
}

func (s *causetnet) SetTLSState(tlsState *tls.ConnectionState) {
	// If user is not connected via TLS, then tlsState == nil.
	if tlsState != nil {
		s.causetnetVars.TLSConnectionState = tlsState
	}
}

func (s *causetnet) SetCommandValue(command byte) {
	atomic.StoreUint32(&s.causetnetVars.CommandValue, uint32(command))
}

func (s *causetnet) SetCollation(coID int) error {
	cs, co, err := charset.GetCharsetInfoByID(coID)
	if err != nil {
		return err
	}
	for _, v := range variable.SetNamesVariables {
		terror.Log(s.causetnetVars.SetSystemVar(v, cs))
	}
	return s.causetnetVars.SetSystemVar(variable.CollationConnection, co)
}

func (s *causetnet) PreparedPlanCache() *kvcache.SimpleLRUCache {
	return s.preparedPlanCache
}

func (s *causetnet) SetCausetnetManager(sm util.CausetnetManager) {
	s.causetnetManager = sm
}

func (s *causetnet) GetCausetnetManager() util.CausetnetManager {
	return s.causetnetManager
}

func (s *causetnet) StoreQueryFeedback(feedback interface{}) {
	if s.statsCollector != nil {
		do, err := GetDomain(s.store)
		if err != nil {
			logutil.BgLogger().Debug("domain not found", zap.Error(err))
			metrics.StoreQueryFeedbackCounter.WithLabelValues(metrics.LblError).Inc()
			return
		}
		err = s.statsCollector.StoreQueryFeedback(feedback, do.StatsHandle())
		if err != nil {
			logutil.BgLogger().Debug("store query feedback", zap.Error(err))
			metrics.StoreQueryFeedbackCounter.WithLabelValues(metrics.LblError).Inc()
			return
		}
		metrics.StoreQueryFeedbackCounter.WithLabelValues(metrics.LblOK).Inc()
	}
}

// FieldList returns fields list of a table.
func (s *causetnet) FieldList(tableName string) ([]*ast.ResultField, error) {
	is := schemareplicant.Getschemareplicant(s)
	dbName := serial.NewCIStr(s.GetCausetnetVars().CurrentDB)
	tName := serial.NewCIStr(tableName)
	table, err := is.TableByName(dbName, tName)
	if err != nil {
		return nil, err
	}

	cols := table.Cols()
	fields := make([]*ast.ResultField, 0, len(cols))
	for _, col := range table.Cols() {
		rf := &ast.ResultField{
			ColumnAsName: col.Name,
			TableAsName:  tName,
			DBName:       dbName,
			Block:        table.Meta(),
			Column:       col.ColumnInfo,
		}
		fields = append(fields, rf)
	}
	return fields, nil
}

func (s *causetnet) doCommit(ctx context.Context) error {
	if !s.txn.Valid() {
		return nil
	}
	defer func() {
		s.txn.changeToInvalid()
		s.causetnetVars.SetStatusFlag(mysql.ServerStatusInTrans, false)
	}()
	if s.txn.IsReadOnly() {
		return nil
	}

	// mockCommitError and mockGetTSErrorInRetry use to test PR #8743.
	ares_centroid_error.Inject("mockCommitError", func(val ares_centroid_error.Value) {
		if val.(bool) && ekv.IsMockCommitErrorEnable() {
			ekv.MockCommitErrorDisable()
			ares_centroid_error.Return(ekv.ErrTxnRetryable)
		}
	})

	if s.causetnetVars.BinlogClient != nil {
		prewriteValue := binloginfo.GetPrewriteValue(s, false)
		if prewriteValue != nil {
			prewriteData, err := prewriteValue.Marshal()
			if err != nil {
				return errors.Trace(err)
			}
			info := &binloginfo.BinlogInfo{
				Data: &binlog.Binlog{
					Tp:            binlog.BinlogType_Prewrite,
					PrewriteValue: prewriteData,
				},
				Client: s.causetnetVars.BinlogClient,
			}
			s.txn.SetOption(ekv.BinlogInfo, info)
		}
	}

	// Get the related table or partition IDs.
	relatedPhysicalTables := s.GetCausetnetVars().TxnCtx.TableDeltaMap
	physicalTableIDs := make([]int64, 0, len(relatedPhysicalTables))
	for id := range relatedPhysicalTables {
		physicalTableIDs = append(physicalTableIDs, id)
	}
	// Set this option for 2 phase commit to validate schema lease.
	s.txn.SetOption(ekv.SchemaChecker, domain.NewSchemaChecker(domain.GetDomain(s), s.causetnetVars.TxnCtx.SchemaVersion, physicalTableIDs))
	s.txn.SetOption(ekv.schemareplicant, s.causetnetVars.TxnCtx.schemareplicant)

	return s.txn.Commit(causetnetctx.SetCommitCtx(ctx, s))
}

func (s *causetnet) doCommitWithRetry(ctx context.Context) error {
	defer func() {
		s.GetCausetnetVars().SetTxnIsolationLevelOneShotStateForNextTxn()
		s.txn.changeToInvalid()
		s.cleanRetryInfo()
	}()
	if !s.txn.Valid() {
		// If the transaction is invalid, maybe it has already been rolled back by the client.
		return nil
	}
	txnSize := s.txn.Size()
	isPessimistic := s.txn.IsPessimistic()
	if span := opentracing.SpanFromContext(ctx); span != nil && span.Tracer() != nil {
		span1 := span.Tracer().StartSpan("causetnet.doCommitWitRetry", opentracing.ChildOf(span.Context()))
		defer span1.Finish()
		ctx = opentracing.ContextWithSpan(ctx, span1)
	}
	err := s.doCommit(ctx)
	if err != nil {
		commitRetryLimit := s.causetnetVars.RetryLimit
		if !s.causetnetVars.TxnCtx.CouldRetry {
			commitRetryLimit = 0
		}
		// Don't retry in BatchInsert mode. As a counter-example, insert into t1 select * from t2,
		// BatchInsert already commit the first batch 1000 rows, then it commit 1000-2000 and retry the statement,
		// Finally t1 will have more data than t2, with no errors return to user!
		if s.isTxnRetryableError(err) && !s.causetnetVars.BatchInsert && commitRetryLimit > 0 && !isPessimistic {
			logutil.Logger(ctx).Warn("sql",
				zap.String("label", s.getSQLLabel()),
				zap.Error(err),
				zap.String("txn", s.txn.GoString()))
			// Transactions will retry 2 ~ commitRetryLimit times.
			// We make larger transactions retry less times to prevent cluster resource outage.
			txnSizeRate := float64(txnSize) / float64(ekv.TxnTotalSizeLimit)
			maxRetryCount := commitRetryLimit - int64(float64(commitRetryLimit-1)*txnSizeRate)
			err = s.retry(ctx, uint(maxRetryCount))
		} else {
			logutil.Logger(ctx).Warn("can not retry txn",
				zap.String("label", s.getSQLLabel()),
				zap.Error(err),
				zap.Bool("IsBatchInsert", s.causetnetVars.BatchInsert),
				zap.Bool("IsPessimistic", isPessimistic),
				zap.Bool("InRestrictedSQL", s.causetnetVars.InRestrictedSQL),
				zap.Int64("MilevaDB_retry_limit", s.causetnetVars.RetryLimit),
				zap.Bool("MilevaDB_disable_txn_auto_retry", s.causetnetVars.DisableTxnAutoRetry))
		}

	}
	counter := s.causetnetVars.TxnCtx.StatementCount
	duration := time.Since(s.GetCausetnetVars().TxnCtx.CreateTime).Seconds()
	s.recordOnTransactionExecution(err, counter, duration)

	if err != nil {
		logutil.Logger(ctx).Warn("commit failed",
			zap.String("finished txn", s.txn.GoString()),
			zap.Error(err))
		return err
	}
	mapper := s.GetCausetnetVars().TxnCtx.TableDeltaMap
	if s.statsCollector != nil && mapper != nil {
		for id, item := range mapper {
			s.statsCollector.Update(id, item.Delta, item.Count, &item.ColSize)
		}
	}
	return nil
}

func (s *causetnet) CommitTxn(ctx context.Context) error {
	if span := opentracing.SpanFromContext(ctx); span != nil && span.Tracer() != nil {
		span1 := span.Tracer().StartSpan("causetnet.CommitTxn", opentracing.ChildOf(span.Context()))
		defer span1.Finish()
		ctx = opentracing.ContextWithSpan(ctx, span1)
	}

	var commitDetail *execdetails.CommitDetails
	ctx = context.WithValue(ctx, execdetails.CommitDetailCtxKey, &commitDetail)
	err := s.doCommitWithRetry(ctx)
	if commitDetail != nil {
		s.causetnetVars.StmtCtx.MergeExecDetails(nil, commitDetail)
	}

	ares_centroid_error.Inject("keepHistory", func(val ares_centroid_error.Value) {
		if val.(bool) {
			ares_centroid_error.Return(err)
		}
	})

	s.causetnetVars.TxnCtx.Cleanup()
	return err
}

func (s *causetnet) RollbackTxn(ctx context.Context) {
	if span := opentracing.SpanFromContext(ctx); span != nil && span.Tracer() != nil {
		span1 := span.Tracer().StartSpan("causetnet.RollbackTxn", opentracing.ChildOf(span.Context()))
		defer span1.Finish()
	}

	if s.txn.Valid() {
		terror.Log(s.txn.Rollback())
	}
	if ctx.Value(inCloseCausetnet{}) == nil {
		s.cleanRetryInfo()
	}
	s.txn.changeToInvalid()
	s.causetnetVars.TxnCtx.Cleanup()
	s.causetnetVars.SetStatusFlag(mysql.ServerStatusInTrans, false)
}

func (s *causetnet) GetClient() ekv.Client {
	return s.client
}

func (s *causetnet) String() string {
	// TODO: how to print binded context in values appropriately?
	sessVars := s.causetnetVars
	data := map[string]interface{}{
		"id":         sessVars.ConnectionID,
		"user":       sessVars.User,
		"currDBName": sessVars.CurrentDB,
		"status":     sessVars.Status,
		"strictMode": sessVars.StrictSQLMode,
	}
	if s.txn.Valid() {
		// if txn is committed or rolled back, txn is nil.
		data["txn"] = s.txn.String()
	}
	if sessVars.SnapshotTS != 0 {
		data["snapshotTS"] = sessVars.SnapshotTS
	}
	if sessVars.StmtCtx.LastInsertID > 0 {
		data["lastInsertID"] = sessVars.StmtCtx.LastInsertID
	}
	if len(sessVars.PreparedStmts) > 0 {
		data["preparedStmtCount"] = len(sessVars.PreparedStmts)
	}
	b, err := json.MarshalIndent(data, "", "  ")
	terror.Log(errors.Trace(err))
	return string(b)
}

const sqlLogMaxLen = 1024

// SchemaChangedWithoutRetry is used for testing.
var SchemaChangedWithoutRetry uint32

func (s *causetnet) getSQLLabel() string {
	if s.causetnetVars.InRestrictedSQL {
		return metrics.LblInternal
	}
	return metrics.LblGeneral
}

func (s *causetnet) isInternal() bool {
	return s.causetnetVars.InRestrictedSQL
}

func (s *causetnet) isTxnRetryableError(err error) bool {
	if atomic.LoadUint32(&SchemaChangedWithoutRetry) == 1 {
		return ekv.IsTxnRetryableError(err)
	}
	return ekv.IsTxnRetryableError(err) || domain.ErrschemareplicantChanged.Equal(err)
}

func (s *causetnet) checkTxnAborted(stmt sqlexec.Statement) error {
	var err error
	if s.txn.doNotCommit != nil {
		err = errors.New("current transaction is aborted, commands ignored until end of transaction block:" + s.txn.doNotCommit.Error())
	} else if atomic.LoadUint32(&s.GetCausetnetVars().TxnCtx.LockExpire) > 0 {
		err = einsteindb.ErrLockExpire
	} else {
		return nil
	}
	// If the transaction is aborted, the following statements do not need to execute, except `commit` and `rollback`,
	// because they are used to finish the aborted transaction.
	if _, ok := stmt.(*Interlock.ExecStmt).StmtNode.(*ast.CommitStmt); ok {
		return nil
	}
	if _, ok := stmt.(*Interlock.ExecStmt).StmtNode.(*ast.RollbackStmt); ok {
		return nil
	}
	return err
}

func (s *causetnet) retry(ctx context.Context, maxCnt uint) (err error) {
	var retryCnt uint
	defer func() {
		s.causetnetVars.RetryInfo.Retrying = false
		// retryCnt only increments on retryable error, so +1 here.
		metrics.CausetnetRetry.Observe(float64(retryCnt + 1))
		s.causetnetVars.SetStatusFlag(mysql.ServerStatusInTrans, false)
		if err != nil {
			s.RollbackTxn(ctx)
		}
		s.txn.changeToInvalid()
	}()

	connID := s.causetnetVars.ConnectionID
	s.causetnetVars.RetryInfo.Retrying = true
	if s.causetnetVars.TxnCtx.ForUpdate {
		err = ErrForUpdateCantRetry.GenWithStackByArgs(connID)
		return err
	}

	nh := GetHistory(s)
	var schemaVersion int64
	sessVars := s.GetCausetnetVars()
	orgStartTS := sessVars.TxnCtx.StartTS
	label := s.getSQLLabel()
	for {
		s.PrepareTxnCtx(ctx)
		s.causetnetVars.RetryInfo.ResetOffset()
		for i, sr := range nh.history {
			st := sr.st
			s.causetnetVars.StmtCtx = sr.stmtCtx
			s.causetnetVars.StmtCtx.ResetForRetry()
			s.causetnetVars.PreparedParams = s.causetnetVars.PreparedParams[:0]
			schemaVersion, err = st.RebuildPlan(ctx)
			if err != nil {
				return err
			}

			if retryCnt == 0 {
				// We do not have to log the query every time.
				// We print the queries at the first try only.
				logutil.Logger(ctx).Warn("retrying",
					zap.Int64("schemaVersion", schemaVersion),
					zap.Uint("retryCnt", retryCnt),
					zap.Int("queryNum", i),
					zap.String("sql", sqlForLog(st.OriginText())+sessVars.PreparedParams.String()))
			} else {
				logutil.Logger(ctx).Warn("retrying",
					zap.Int64("schemaVersion", schemaVersion),
					zap.Uint("retryCnt", retryCnt),
					zap.Int("queryNum", i))
			}
			_, err = st.Exec(ctx)
			if err != nil {
				s.StmtRollback()
				break
			}
			// We do not need to pass memTracker here, because that retry
			// happened after commit, the memory usage was calculated during the
			// first execution.
			err = s.StmtCommit(nil)
			if err != nil {
				return err
			}
		}
		logutil.Logger(ctx).Warn("transaction association",
			zap.Uint64("retrying txnStartTS", s.GetCausetnetVars().TxnCtx.StartTS),
			zap.Uint64("original txnStartTS", orgStartTS))
		ares_centroid_error.Inject("preCommitHook", func() {
			hook, ok := ctx.Value("__preCommitHook").(func())
			if ok {
				hook()
			}
		})
		if err == nil {
			err = s.doCommit(ctx)
			if err == nil {
				break
			}
		}
		if !s.isTxnRetryableError(err) {
			logutil.Logger(ctx).Warn("sql",
				zap.String("label", label),
				zap.Stringer("causetnet", s),
				zap.Error(err))
			metrics.CausetnetRetryErrorCounter.WithLabelValues(label, metrics.LblUnretryable).Inc()
			return err
		}
		retryCnt++
		if retryCnt >= maxCnt {
			logutil.Logger(ctx).Warn("sql",
				zap.String("label", label),
				zap.Uint("retry reached max count", retryCnt))
			metrics.CausetnetRetryErrorCounter.WithLabelValues(label, metrics.LblReachMax).Inc()
			return err
		}
		logutil.Logger(ctx).Warn("sql",
			zap.String("label", label),
			zap.Error(err),
			zap.String("txn", s.txn.GoString()))
		ekv.BackOff(retryCnt)
		s.txn.changeToInvalid()
		s.causetnetVars.SetStatusFlag(mysql.ServerStatusInTrans, false)
	}
	return err
}

func sqlForLog(sql string) string {
	if len(sql) > sqlLogMaxLen {
		sql = sql[:sqlLogMaxLen] + fmt.Sprintf("(len:%d)", len(sql))
	}
	return Interlock.QueryReplacer.Replace(sql)
}

type causetnetPool interface {
	Get() (pools.Resource, error)
	Put(pools.Resource)
}

func (s *causetnet) sysCausetnetPool() causetnetPool {
	return domain.GetDomain(s).SysCausetnetPool()
}

// ExecRestrictedSQL implements RestrictedSQLInterlock interface.
// This is used for executing some restricted sql statements, usually executed during a normal statement execution.
// Unlike normal Exec, it doesn't reset statement status, doesn't commit or rollback the current transaction
// and doesn't write binlog.
func (s *causetnet) ExecRestrictedSQL(sql string) ([]chunk.Row, []*ast.ResultField, error) {
	return s.ExecRestrictedSQLWithContext(context.TODO(), sql)
}

// ExecRestrictedSQLWithContext implements RestrictedSQLInterlock interface.
func (s *causetnet) ExecRestrictedSQLWithContext(ctx context.Context, sql string) ([]chunk.Row, []*ast.ResultField, error) {
	// Use special causetnet to execute the sql.
	tmp, err := s.sysCausetnetPool().Get()
	if err != nil {
		return nil, nil, err
	}
	se := tmp.(*causetnet)
	// The special causetnet will share the `InspectionTableCache` with current causetnet
	// if the current causetnet in inspection mode.
	if cache := s.causetnetVars.InspectionTableCache; cache != nil {
		se.causetnetVars.InspectionTableCache = cache
		defer func() { se.causetnetVars.InspectionTableCache = nil }()
	}
	if ok := s.causetnetVars.OptimizerUseInvisibleIndexes; ok {
		se.causetnetVars.OptimizerUseInvisibleIndexes = true
		defer func() { se.causetnetVars.OptimizerUseInvisibleIndexes = false }()
	}
	defer func() {
		if se != nil && se.GetCausetnetVars().StmtCtx.WarningCount() > 0 {
			warnings := se.GetCausetnetVars().StmtCtx.GetWarnings()
			s.GetCausetnetVars().StmtCtx.AppendWarnings(warnings)
		}
		s.sysCausetnetPool().Put(tmp)
	}()
	metrics.CausetnetRestrictedSQLCounter.Inc()

	return execRestrictedSQL(ctx, se, sql)
}

// ExecRestrictedSQLWithSnapshot implements RestrictedSQLInterlock interface.
// This is used for executing some restricted sql statements with snapshot.
// If current causetnet sets the snapshot timestamp, then execute with this snapshot timestamp.
// Otherwise, execute with the current transaction start timestamp if the transaction is valid.
func (s *causetnet) ExecRestrictedSQLWithSnapshot(sql string) ([]chunk.Row, []*ast.ResultField, error) {
	ctx := context.TODO()

	// Use special causetnet to execute the sql.
	tmp, err := s.sysCausetnetPool().Get()
	if err != nil {
		return nil, nil, err
	}
	se := tmp.(*causetnet)
	// The special causetnet will share the `InspectionTableCache` with current causetnet
	// if the current causetnet in inspection mode.
	if cache := s.causetnetVars.InspectionTableCache; cache != nil {
		se.causetnetVars.InspectionTableCache = cache
		defer func() { se.causetnetVars.InspectionTableCache = nil }()
	}
	defer s.sysCausetnetPool().Put(tmp)
	metrics.CausetnetRestrictedSQLCounter.Inc()
	var snapshot uint64
	txn, err := s.Txn(false)
	if err != nil {
		return nil, nil, err
	}
	if txn.Valid() {
		snapshot = s.txn.StartTS()
	}
	if s.causetnetVars.SnapshotTS != 0 {
		snapshot = s.causetnetVars.SnapshotTS
	}
	// Set snapshot.
	if snapshot != 0 {
		se.causetnetVars.Snapshotschemareplicant, err = domain.GetDomain(s).GetSnapshotschemareplicant(snapshot)
		if err != nil {
			return nil, nil, err
		}
		if err := se.causetnetVars.SetSystemVar(variable.MilevaDBSnapshot, strconv.FormatUint(snapshot, 10)); err != nil {
			return nil, nil, err
		}
		defer func() {
			if err := se.causetnetVars.SetSystemVar(variable.MilevaDBSnapshot, ""); err != nil {
				logutil.BgLogger().Error("set MilevaDBSnapshot error", zap.Error(err))
			}
			se.causetnetVars.Snapshotschemareplicant = nil
		}()
	}
	if ok := s.causetnetVars.OptimizerUseInvisibleIndexes; ok {
		se.causetnetVars.OptimizerUseInvisibleIndexes = true
		defer func() { se.causetnetVars.OptimizerUseInvisibleIndexes = false }()
	}
	return execRestrictedSQL(ctx, se, sql)
}

func execRestrictedSQL(ctx context.Context, se *causetnet, sql string) ([]chunk.Row, []*ast.ResultField, error) {
	ctx = context.WithValue(ctx, execdetails.StmtExecDetailKey, &execdetails.StmtExecDetails{})
	startTime := time.Now()
	recordSets, err := se.Execute(ctx, sql)
	if err != nil {
		return nil, nil, err
	}

	var (
		rows   []chunk.Row
		fields []*ast.ResultField
	)
	// Execute all recordset, take out the first one as result.
	for i, rs := range recordSets {
		tmp, err := drainRecordSet(ctx, se, rs)
		if err != nil {
			return nil, nil, err
		}
		if err = rs.Close(); err != nil {
			return nil, nil, err
		}

		if i == 0 {
			rows = tmp
			fields = rs.Fields()
		}
	}
	metrics.QueryDurationHistogram.WithLabelValues(metrics.LblInternal).Observe(time.Since(startTime).Seconds())
	return rows, fields, nil
}

func createCausetnetFunc(store ekv.Storage) pools.Factory {
	return func() (pools.Resource, error) {
		se, err := createCausetnet(store)
		if err != nil {
			return nil, err
		}
		err = variable.SetCausetnetSystemVar(se.causetnetVars, variable.AutoCommit, types.NewStringCausetObjectQL("1"))
		if err != nil {
			return nil, err
		}
		err = variable.SetCausetnetSystemVar(se.causetnetVars, variable.MaxExecutionTime, types.NewUintCausetObjectQL(0))
		if err != nil {
			return nil, errors.Trace(err)
		}
		err = variable.SetCausetnetSystemVar(se.causetnetVars, variable.MaxAllowedPacket, types.NewStringCausetObjectQL("67108864"))
		if err != nil {
			return nil, errors.Trace(err)
		}
		se.causetnetVars.CommonGlobalLoaded = true
		se.causetnetVars.InRestrictedSQL = true
		return se, nil
	}
}

func createCausetnetWithDomainFunc(store ekv.Storage) func(*domain.Domain) (pools.Resource, error) {
	return func(dom *domain.Domain) (pools.Resource, error) {
		se, err := CreateCausetnetWithDomain(store, dom)
		if err != nil {
			return nil, err
		}
		err = variable.SetCausetnetSystemVar(se.causetnetVars, variable.AutoCommit, types.NewStringCausetObjectQL("1"))
		if err != nil {
			return nil, err
		}
		err = variable.SetCausetnetSystemVar(se.causetnetVars, variable.MaxExecutionTime, types.NewUintCausetObjectQL(0))
		if err != nil {
			return nil, errors.Trace(err)
		}
		se.causetnetVars.CommonGlobalLoaded = true
		se.causetnetVars.InRestrictedSQL = true
		return se, nil
	}
}

func drainRecordSet(ctx context.Context, se *causetnet, rs sqlexec.RecordSet) ([]chunk.Row, error) {
	var rows []chunk.Row
	req := rs.NewChunk()
	for {
		err := rs.Next(ctx, req)
		if err != nil || req.NumRows() == 0 {
			return rows, err
		}
		iter := chunk.NewIterator4Chunk(req)
		for r := iter.Begin(); r != iter.End(); r = iter.Next() {
			rows = append(rows, r)
		}
		req = chunk.Renew(req, se.causetnetVars.MaxChunkSize)
	}
}

// getExecRet executes restricted sql and the result is one column.
// It returns a string value.
func (s *causetnet) getExecRet(ctx causetnetctx.Context, sql string) (string, error) {
	rows, fields, err := s.ExecRestrictedSQL(sql)
	if err != nil {
		return "", err
	}
	if len(rows) == 0 {
		return "", Interlock.ErrResultIsEmpty
	}
	d := rows[0].GetCausetObjectQL(0, &fields[0].Column.FieldType)
	value, err := d.ToString()
	if err != nil {
		return "", err
	}
	return value, nil
}

// GetAllSysVars implements GlobalVarAccessor.GetAllSysVars interface.
func (s *causetnet) GetAllSysVars() (map[string]string, error) {
	if s.Value(causetnetctx.Initing) != nil {
		return nil, nil
	}
	sql := `SELECT VARIABLE_NAME, VARIABLE_VALUE FROM %s.%s;`
	sql = fmt.Sprintf(sql, mysql.SystemDB, mysql.GlobalVariablesTable)
	rows, _, err := s.ExecRestrictedSQL(sql)
	if err != nil {
		return nil, err
	}
	ret := make(map[string]string, len(rows))
	for _, r := range rows {
		k, v := r.GetString(0), r.GetString(1)
		ret[k] = v
	}
	return ret, nil
}

// GetGlobalSysVar implements GlobalVarAccessor.GetGlobalSysVar interface.
func (s *causetnet) GetGlobalSysVar(name string) (string, error) {
	if s.Value(causetnetctx.Initing) != nil {
		// When running bootstrap or upgrade, we should not access global storage.
		return "", nil
	}
	sql := fmt.Sprintf(`SELECT VARIABLE_VALUE FROM %s.%s WHERE VARIABLE_NAME="%s";`,
		mysql.SystemDB, mysql.GlobalVariablesTable, name)
	sysVar, err := s.getExecRet(s, sql)
	if err != nil {
		if Interlock.ErrResultIsEmpty.Equal(err) {
			if sv, ok := variable.SysVars[name]; ok {
				return sv.Value, nil
			}
			return "", variable.ErrUnknownSystemVar.GenWithStackByArgs(name)
		}
		return "", err
	}
	return sysVar, nil
}

// SetGlobalSysVar implements GlobalVarAccessor.SetGlobalSysVar interface.
func (s *causetnet) SetGlobalSysVar(name, value string) error {
	if name == variable.SQLModeVar {
		value = mysql.FormatSQLModeStr(value)
		if _, err := mysql.GetSQLMode(value); err != nil {
			return err
		}
	}
	var sVal string
	var err error
	sVal, err = variable.ValidateSetSystemVar(s.causetnetVars, name, value, variable.SINTERLOCKeGlobal)
	if err != nil {
		return err
	}
	name = strings.ToLower(name)
	sql := fmt.Sprintf(`REPLACE %s.%s VALUES ('%s', '%s');`,
		mysql.SystemDB, mysql.GlobalVariablesTable, name, sVal)
	_, _, err = s.ExecRestrictedSQL(sql)
	return err
}

func (s *causetnet) ParseSQL(ctx context.Context, sql, charset, collation string) ([]ast.StmtNode, []error, error) {
	if span := opentracing.SpanFromContext(ctx); span != nil && span.Tracer() != nil {
		span1 := span.Tracer().StartSpan("causetnet.ParseSQL", opentracing.ChildOf(span.Context()))
		defer span1.Finish()
	}
	s.BerolinaSQL.SetSQLMode(s.causetnetVars.SQLMode)
	s.BerolinaSQL.EnableWindowFunc(s.causetnetVars.EnableWindowFunction)
	return s.BerolinaSQL.Parse(sql, charset, collation)
}

func (s *causetnet) SetProcessInfo(sql string, t time.Time, command byte, maxExecutionTime uint64) {
	// If command == mysql.ComSleep, it means the SQL execution is finished. The processinfo is reset to SLEEP.
	// If the SQL finished and the causetnet is not in transaction, the current start timestamp need to reset to 0.
	// Otherwise, it should be set to the transaction start timestamp.
	// Why not reset the transaction start timestamp to 0 when transaction committed?
	// Because the select statement and other statements need this timestamp to read data,
	// after the transaction is committed. e.g. SHOW MASTER STATUS;
	var curTxnStartTS uint64
	if command != mysql.ComSleep || s.GetCausetnetVars().InTxn() {
		curTxnStartTS = s.causetnetVars.TxnCtx.StartTS
	}
	pi := util.ProcessInfo{
		ID:               s.causetnetVars.ConnectionID,
		DB:               s.causetnetVars.CurrentDB,
		Command:          command,
		Plan:             s.currentPlan,
		PlanExplainRows:  plannercore.GetExplainRowsForPlan(s.currentPlan),
		Time:             t,
		State:            s.Status(),
		Info:             sql,
		CurTxnStartTS:    curTxnStartTS,
		StmtCtx:          s.causetnetVars.StmtCtx,
		StatsInfo:        plannercore.GetStatsInfo,
		MaxExecutionTime: maxExecutionTime,
	}
	if s.causetnetVars.User != nil {
		pi.User = s.causetnetVars.User.Username
		pi.Host = s.causetnetVars.User.Hostname
	}
	s.processInfo.Store(&pi)
}

func (s *causetnet) ExecuteInternal(ctx context.Context, sql string) (recordSets []sqlexec.RecordSet, err error) {
	origin := s.causetnetVars.InRestrictedSQL
	s.causetnetVars.InRestrictedSQL = true
	defer func() {
		s.causetnetVars.InRestrictedSQL = origin
	}()
	return s.Execute(ctx, sql)
}

func (s *causetnet) Execute(ctx context.Context, sql string) (recordSets []sqlexec.RecordSet, err error) {
	if span := opentracing.SpanFromContext(ctx); span != nil && span.Tracer() != nil {
		span1 := span.Tracer().StartSpan("causetnet.Execute", opentracing.ChildOf(span.Context()))
		defer span1.Finish()
		ctx = opentracing.ContextWithSpan(ctx, span1)
		logutil.Eventf(ctx, "execute: %s", sql)
	}

	charsetInfo, collation := s.causetnetVars.GetCharsetInfo()
	parseStartTime := time.Now()
	stmtNodes, warns, err := s.ParseSQL(ctx, sql, charsetInfo, collation)
	if err != nil {
		s.rollbackOnError(ctx)

		// Only print log message when this SQL is from the user.
		// Mute the warning for internal SQLs.
		if !s.causetnetVars.InRestrictedSQL {
			logutil.Logger(ctx).Warn("parse SQL failed", zap.Error(err), zap.String("SQL", sql))
		}
		return nil, util.SyntaxError(err)
	}
	if len(stmtNodes) != 1 {
		return nil, errors.New("Execute() API doesn't support multiple statements any more")
	}
	durParse := time.Since(parseStartTime)
	s.GetCausetnetVars().DurationParse = durParse

	rs, err := s.ExecuteStmt(ctx, stmtNodes[0])
	if err != nil {
		s.causetnetVars.StmtCtx.AppendError(err)
	}
	for _, warn := range warns {
		s.causetnetVars.StmtCtx.AppendWarning(util.SyntaxWarn(warn))
	}
	if rs == nil {
		return nil, err
	}
	return []sqlexec.RecordSet{rs}, err
}

// Parse parses a query string to raw ast.StmtNode.
func (s *causetnet) Parse(ctx context.Context, sql string) ([]ast.StmtNode, error) {
	charsetInfo, collation := s.causetnetVars.GetCharsetInfo()
	parseStartTime := time.Now()
	stmts, warns, err := s.ParseSQL(ctx, sql, charsetInfo, collation)
	if err != nil {
		s.rollbackOnError(ctx)

		// Only print log message when this SQL is from the user.
		// Mute the warning for internal SQLs.
		if !s.causetnetVars.InRestrictedSQL {
			logutil.Logger(ctx).Warn("parse SQL failed", zap.Error(err), zap.String("SQL", sql))
		}
		return nil, util.SyntaxError(err)
	}

	durParse := time.Since(parseStartTime)
	s.GetCausetnetVars().DurationParse = durParse
	isInternal := s.isInternal()
	if isInternal {
		causetnetExecuteParseDurationInternal.Observe(durParse.Seconds())
	} else {
		causetnetExecuteParseDurationGeneral.Observe(durParse.Seconds())
	}
	for _, warn := range warns {
		s.causetnetVars.StmtCtx.AppendWarning(util.SyntaxWarn(warn))
	}
	return stmts, nil
}

func (s *causetnet) ExecuteStmt(ctx context.Context, stmtNode ast.StmtNode) (sqlexec.RecordSet, error) {
	if span := opentracing.SpanFromContext(ctx); span != nil && span.Tracer() != nil {
		span1 := span.Tracer().StartSpan("causetnet.ExecuteStmt", opentracing.ChildOf(span.Context()))
		defer span1.Finish()
		ctx = opentracing.ContextWithSpan(ctx, span1)
	}

	s.PrepareTxnCtx(ctx)
	err := s.loadCommonGlobalVariablesIfNeeded()
	if err != nil {
		return nil, err
	}

	s.causetnetVars.StartTime = time.Now()

	// Some executions are done in compile stage, so we reset them before compile.
	if err := Interlock.ResetContextOfStmt(s, stmtNode); err != nil {
		return nil, err
	}

	// Transform abstract syntax tree to a physical plan(stored in Interlock.ExecStmt).
	compiler := Interlock.Compiler{Ctx: s}
	stmt, err := compiler.Compile(ctx, stmtNode)
	if err != nil {
		s.rollbackOnError(ctx)

		// Only print log message when this SQL is from the user.
		// Mute the warning for internal SQLs.
		if !s.causetnetVars.InRestrictedSQL {
			logutil.Logger(ctx).Warn("compile SQL failed", zap.Error(err), zap.String("SQL", stmtNode.Text()))
		}
		return nil, err
	}
	durCompile := time.Since(s.causetnetVars.StartTime)
	s.GetCausetnetVars().DurationCompile = durCompile
	if s.isInternal() {
		causetnetExecuteCompileDurationInternal.Observe(durCompile.Seconds())
	} else {
		causetnetExecuteCompileDurationGeneral.Observe(durCompile.Seconds())
	}
	s.currentPlan = stmt.Plan

	// Execute the physical plan.
	logStmt(stmtNode, s.causetnetVars)
	recordSet, err := runStmt(ctx, s, stmt)
	if err != nil {
		if !ekv.ErrKeyExists.Equal(err) {
			logutil.Logger(ctx).Warn("run statement failed",
				zap.Int64("schemaVersion", s.causetnetVars.TxnCtx.SchemaVersion),
				zap.Error(err),
				zap.String("causetnet", s.String()))
		}
		return nil, err
	}
	return recordSet, nil
}

// runStmt executes the sqlexec.Statement and commit or rollback the current transaction.
func runStmt(ctx context.Context, se *causetnet, s sqlexec.Statement) (rs sqlexec.RecordSet, err error) {
	if span := opentracing.SpanFromContext(ctx); span != nil && span.Tracer() != nil {
		span1 := span.Tracer().StartSpan("causetnet.runStmt", opentracing.ChildOf(span.Context()))
		span1.LogKV("sql", s.OriginText())
		defer span1.Finish()
		ctx = opentracing.ContextWithSpan(ctx, span1)
	}
	se.SetValue(causetnetctx.QueryString, s.OriginText())
	if _, ok := s.(*Interlock.ExecStmt).StmtNode.(ast.DDLNode); ok {
		se.SetValue(causetnetctx.LastExecuteDDL, true)
	} else {
		se.ClearValue(causetnetctx.LastExecuteDDL)
	}

	sessVars := se.causetnetVars
	// Save origTxnCtx here to avoid it reset in the transaction retry.
	origTxnCtx := sessVars.TxnCtx
	err = se.checkTxnAborted(s)
	if err != nil {
		return nil, err
	}
	rs, err = s.Exec(ctx)
	sessVars.TxnCtx.StatementCount++
	if !s.IsReadOnly(sessVars) {
		// All the history should be added here.
		if err == nil && sessVars.TxnCtx.CouldRetry {
			GetHistory(se).Add(s, sessVars.StmtCtx)
		}

		// Handle the stmt commit/rollback.
		if se.txn.Valid() {
			if err != nil {
				se.StmtRollback()
			} else {
				err = se.StmtCommit(sessVars.StmtCtx.MemTracker)
			}
		}
	}
	if rs != nil {
		return &execStmtResult{
			RecordSet: rs,
			sql:       s,
			se:        se,
		}, err
	}

	err = finishStmt(ctx, se, err, s)

	// If it is not a select statement, we record its slow log here,
	// then it could include the transaction commit time.
	s.(*Interlock.ExecStmt).FinishExecuteStmt(origTxnCtx.StartTS, err == nil, false)
	return nil, err
}

// execStmtResult is the return value of ExecuteStmt and it implements the sqlexec.RecordSet interface.
// Why we need a struct to wrap a RecordSet and provide another RecordSet?
// This is because there are so many causetnet state related things that definitely not belongs to the original
// RecordSet, so this struct exists and RecordSet.Close() is overrided handle that.
type execStmtResult struct {
	sqlexec.RecordSet
	se  *causetnet
	sql sqlexec.Statement
}

func (rs *execStmtResult) Close() error {
	se := rs.se
	err := rs.RecordSet.Close()
	return finishStmt(context.Background(), se, err, rs.sql)
}

// rollbackOnError makes sure the next statement starts a new transaction with the latest schemareplicant.
func (s *causetnet) rollbackOnError(ctx context.Context) {
	if !s.causetnetVars.InTxn() {
		s.RollbackTxn(ctx)
	}
}

// PrepareStmt is used for executing prepare statement in binary protocol
func (s *causetnet) PrepareStmt(sql string) (stmtID uint32, paramCount int, fields []*ast.ResultField, err error) {
	if s.causetnetVars.TxnCtx.schemareplicant == nil {
		// We don't need to create a transaction for prepare statement, just get information schema will do.
		s.causetnetVars.TxnCtx.schemareplicant = domain.GetDomain(s).schemareplicant()
	}
	err = s.loadCommonGlobalVariablesIfNeeded()
	if err != nil {
		return
	}

	ctx := context.Background()
	inTxn := s.GetCausetnetVars().InTxn()
	// NewPrepareExec may need startTS to build the Interlock, for example prepare statement has subquery in int.
	// So we have to call PrepareTxnCtx here.
	s.PrepareTxnCtx(ctx)
	s.PrepareTSFuture(ctx)
	prepareExec := Interlock.NewPrepareExec(s, schemareplicant.Getschemareplicant(s), sql)
	err = prepareExec.Next(ctx, nil)
	if err != nil {
		return
	}
	if !inTxn {
		// We could start a transaction to build the prepare Interlock before, we should rollback it here.
		s.RollbackTxn(ctx)
	}
	return prepareExec.ID, prepareExec.ParamCount, prepareExec.Fields, nil
}

func (s *causetnet) preparedStmtExec(ctx context.Context,
	stmtID uint32, prepareStmt *plannercore.CachedPrepareStmt, args []types.CausetObjectQL) (sqlexec.RecordSet, error) {
	st, err := Interlock.CompileExecutePreparedStmt(ctx, s, stmtID, args)
	if err != nil {
		return nil, err
	}
	causetnetExecuteCompileDurationGeneral.Observe(time.Since(s.causetnetVars.StartTime).Seconds())
	logQuery(st.OriginText(), s.causetnetVars)
	return runStmt(ctx, s, st)
}

// cachedPlanExec short path currently ONLY for cached "point select plan" execution
func (s *causetnet) cachedPlanExec(ctx context.Context,
	stmtID uint32, prepareStmt *plannercore.CachedPrepareStmt, args []types.CausetObjectQL) (sqlexec.RecordSet, error) {
	prepared := prepareStmt.PreparedAst
	// compile ExecStmt
	is := schemareplicant.Getschemareplicant(s)
	execAst := &ast.ExecuteStmt{ExecID: stmtID}
	if err := Interlock.ResetContextOfStmt(s, execAst); err != nil {
		return nil, err
	}
	execAst.BinaryArgs = args
	execPlan, err := planner.OptimizeExecStmt(ctx, s, execAst, is)
	if err != nil {
		return nil, err
	}

	stmtCtx := s.GetCausetnetVars().StmtCtx
	stmt := &Interlock.ExecStmt{
		GoCtx:           ctx,
		schemareplicant: is,
		Plan:            execPlan,
		StmtNode:        execAst,
		Ctx:             s,
		OutputNames:     execPlan.OutputNames(),
		PsStmt:          prepareStmt,
	}
	compileDuration := time.Since(s.causetnetVars.StartTime)
	causetnetExecuteCompileDurationGeneral.Observe(compileDuration.Seconds())
	s.GetCausetnetVars().DurationCompile = compileDuration

	stmt.Text = prepared.Stmt.Text()
	stmtCtx.OriginalSQL = stmt.Text
	stmtCtx.InitSQLDigest(prepareStmt.NormalizedSQL, prepareStmt.SQLDigest)
	stmtCtx.SetPlanDigest(prepareStmt.NormalizedPlan, prepareStmt.PlanDigest)
	logQuery(stmt.OriginText(), s.causetnetVars)

	// run ExecStmt
	var resultSet sqlexec.RecordSet
	switch prepared.CachedPlan.(type) {
	case *plannercore.PointGetPlan:
		resultSet, err = stmt.PointGet(ctx, is)
		s.txn.changeToInvalid()
	case *plannercore.Update:
		s.PrepareTSFuture(ctx)
		stmtCtx.Priority = ekv.PriorityHigh
		resultSet, err = runStmt(ctx, s, stmt)
	default:
		prepared.CachedPlan = nil
		return nil, errors.Errorf("invalid cached plan type")
	}
	return resultSet, err
}

// IsCachedExecOk check if we can execute using plan cached in prepared structure
// Be careful for the short path, current precondition is ths cached plan satisfying
// IsPointGetWithPKOrUniqueKeyByAutoCommit
func (s *causetnet) IsCachedExecOk(ctx context.Context, preparedStmt *plannercore.CachedPrepareStmt) (bool, error) {
	prepared := preparedStmt.PreparedAst
	if prepared.CachedPlan == nil {
		return false, nil
	}
	// check auto commit
	if !s.GetCausetnetVars().IsAutocommit() {
		return false, nil
	}
	// check schema version
	is := schemareplicant.Getschemareplicant(s)
	if prepared.SchemaVersion != is.SchemaMetaVersion() {
		prepared.CachedPlan = nil
		return false, nil
	}
	// maybe we'd better check cached plan type here, current
	// only point select/update will be cached, see "getPhysicalPlan" func
	var ok bool
	var err error
	switch prepared.CachedPlan.(type) {
	case *plannercore.PointGetPlan:
		ok = true
	case *plannercore.Update:
		pointUpdate := prepared.CachedPlan.(*plannercore.Update)
		_, ok = pointUpdate.SelectPlan.(*plannercore.PointGetPlan)
		if !ok {
			err = errors.Errorf("cached update plan not point update")
			prepared.CachedPlan = nil
			return false, err
		}
	default:
		ok = false
	}
	return ok, err
}

// ExecutePreparedStmt executes a prepared statement.
func (s *causetnet) ExecutePreparedStmt(ctx context.Context, stmtID uint32, args []types.CausetObjectQL) (sqlexec.RecordSet, error) {
	s.PrepareTxnCtx(ctx)
	var err error
	s.causetnetVars.StartTime = time.Now()
	preparedPointer, ok := s.causetnetVars.PreparedStmts[stmtID]
	if !ok {
		err = plannercore.ErrStmtNotFound
		logutil.Logger(ctx).Error("prepared statement not found", zap.Uint32("stmtID", stmtID))
		return nil, err
	}
	preparedStmt, ok := preparedPointer.(*plannercore.CachedPrepareStmt)
	if !ok {
		return nil, errors.Errorf("invalid CachedPrepareStmt type")
	}
	Interlock.CountStmtNode(preparedStmt.PreparedAst.Stmt, s.causetnetVars.InRestrictedSQL)
	ok, err = s.IsCachedExecOk(ctx, preparedStmt)
	if err != nil {
		return nil, err
	}
	if ok {
		return s.cachedPlanExec(ctx, stmtID, preparedStmt, args)
	}
	return s.preparedStmtExec(ctx, stmtID, preparedStmt, args)
}

func (s *causetnet) DropPreparedStmt(stmtID uint32) error {
	vars := s.causetnetVars
	if _, ok := vars.PreparedStmts[stmtID]; !ok {
		return plannercore.ErrStmtNotFound
	}
	vars.RetryInfo.DroppedPreparedStmtIDs = append(vars.RetryInfo.DroppedPreparedStmtIDs, stmtID)
	return nil
}

func (s *causetnet) Txn(active bool) (ekv.Transaction, error) {
	if !active {
		return &s.txn, nil
	}
	if !s.txn.validOrPending() {
		return &s.txn, errors.AddStack(ekv.ErrInvalidTxn)
	}
	if s.txn.pending() {
		defer func(begin time.Time) {
			s.causetnetVars.DurationWaitTS = time.Since(begin)
		}(time.Now())
		// Transaction is lazy initialized.
		// PrepareTxnCtx is called to get a tso future, makes s.txn a pending txn,
		// If Txn() is called later, wait for the future to get a valid txn.
		if err := s.txn.changePendingToValid(); err != nil {
			logutil.BgLogger().Error("active transaction fail",
				zap.Error(err))
			s.txn.cleanup()
			s.causetnetVars.TxnCtx.StartTS = 0
			return &s.txn, err
		}
		s.causetnetVars.TxnCtx.StartTS = s.txn.StartTS()
		if s.causetnetVars.TxnCtx.IsPessimistic {
			s.txn.SetOption(ekv.Pessimistic, true)
		}
		if !s.causetnetVars.IsAutocommit() {
			s.causetnetVars.SetStatusFlag(mysql.ServerStatusInTrans, true)
		}
		s.causetnetVars.TxnCtx.CouldRetry = s.isTxnRetryable()
		s.txn.SetVars(s.causetnetVars.KVVars)
		if s.causetnetVars.GetReplicaRead().IsFollowerRead() {
			s.txn.SetOption(ekv.ReplicaRead, ekv.ReplicaReadFollower)
		}
	}
	return &s.txn, nil
}

// isTxnRetryable (if returns true) means the transaction could retry.
// If the transaction is in pessimistic mode, do not retry.
// If the causetnet is already in transaction, enable retry or internal SQL could retry.
// If not, the transaction could always retry, because it should be auto committed transaction.
// Anyway the retry limit is 0, the transaction could not retry.
func (s *causetnet) isTxnRetryable() bool {
	sessVars := s.causetnetVars

	// The pessimistic transaction no need to retry.
	if sessVars.TxnCtx.IsPessimistic {
		return false
	}

	// If retry limit is 0, the transaction could not retry.
	if sessVars.RetryLimit == 0 {
		return false
	}

	// If the causetnet is not InTxn, it is an auto-committed transaction.
	// The auto-committed transaction could always retry.
	if !sessVars.InTxn() {
		return true
	}

	// The internal transaction could always retry.
	if sessVars.InRestrictedSQL {
		return true
	}

	// If the retry is enabled, the transaction could retry.
	if !sessVars.DisableTxnAutoRetry {
		return true
	}

	return false
}

func (s *causetnet) NewTxn(ctx context.Context) error {
	if s.txn.Valid() {
		txnID := s.txn.StartTS()
		err := s.CommitTxn(ctx)
		if err != nil {
			return err
		}
		vars := s.GetCausetnetVars()
		logutil.Logger(ctx).Info("NewTxn() inside a transaction auto commit",
			zap.Int64("schemaVersion", vars.TxnCtx.SchemaVersion),
			zap.Uint64("txnStartTS", txnID))
	}

	txn, err := s.store.Begin()
	if err != nil {
		return err
	}
	txn.SetVars(s.causetnetVars.KVVars)
	if s.GetCausetnetVars().GetReplicaRead().IsFollowerRead() {
		txn.SetOption(ekv.ReplicaRead, ekv.ReplicaReadFollower)
	}
	s.txn.changeInvalidToValid(txn)
	is := domain.GetDomain(s).schemareplicant()
	s.causetnetVars.TxnCtx = &variable.TransactionContext{
		schemareplicant: is,
		SchemaVersion:   is.SchemaMetaVersion(),
		CreateTime:      time.Now(),
		StartTS:         txn.StartTS(),
		ShardStep:       int(s.causetnetVars.ShardAllocateStep),
	}
	return nil
}

func (s *causetnet) SetValue(key fmt.Stringer, value interface{}) {
	s.mu.Lock()
	s.mu.values[key] = value
	s.mu.Unlock()
}

func (s *causetnet) Value(key fmt.Stringer) interface{} {
	s.mu.RLock()
	value := s.mu.values[key]
	s.mu.RUnlock()
	return value
}

func (s *causetnet) ClearValue(key fmt.Stringer) {
	s.mu.Lock()
	delete(s.mu.values, key)
	s.mu.Unlock()
}

type inCloseCausetnet struct{}

// Close function does some clean work when causetnet end.
// Close should release the table locks which hold by the causetnet.
func (s *causetnet) Close() {
	// TODO: do clean table locks when causetnet exited without execute Close.
	// TODO: do clean table locks when MilevaDB-server was `kill -9`.
	if s.HasLockedTables() && config.TableLockEnabled() {
		if ds := config.TableLockDelayClean(); ds > 0 {
			time.Sleep(time.Duration(ds) * time.Millisecond)
		}
		lockedTables := s.GetAllTableLocks()
		err := domain.GetDomain(s).DDL().UnlockTables(s, lockedTables)
		if err != nil {
			logutil.BgLogger().Error("release table dagger failed", zap.Uint64("conn", s.causetnetVars.ConnectionID))
		}
	}
	if s.statsCollector != nil {
		s.statsCollector.Delete()
	}
	bindValue := s.Value(bindinfo.CausetnetBindInfoKeyType)
	if bindValue != nil {
		bindValue.(*bindinfo.CausetnetHandle).Close()
	}
	ctx := context.WithValue(context.TODO(), inCloseCausetnet{}, struct{}{})
	s.RollbackTxn(ctx)
	if s.causetnetVars != nil {
		s.causetnetVars.WithdrawAllPreparedStmt()
	}
}

// GetCausetnetVars implements the context.Context interface.
func (s *causetnet) GetCausetnetVars() *variable.CausetnetVars {
	return s.causetnetVars
}

func (s *causetnet) Auth(user *auth.UserIdentity, authentication []byte, salt []byte) bool {
	pm := privilege.GetPrivilegeManager(s)

	// Check IP or localhost.
	var success bool
	user.AuthUsername, user.AuthHostname, success = pm.ConnectionVerification(user.Username, user.Hostname, authentication, salt, s.causetnetVars.TLSConnectionState)
	if success {
		s.causetnetVars.User = user
		s.causetnetVars.ActiveRoles = pm.GetDefaultRoles(user.AuthUsername, user.AuthHostname)
		return true
	} else if user.Hostname == variable.DefHostname {
		return false
	}

	// Check Hostname.
	for _, addr := range getHostByIP(user.Hostname) {
		u, h, success := pm.ConnectionVerification(user.Username, addr, authentication, salt, s.causetnetVars.TLSConnectionState)
		if success {
			s.causetnetVars.User = &auth.UserIdentity{
				Username:     user.Username,
				Hostname:     addr,
				AuthUsername: u,
				AuthHostname: h,
			}
			s.causetnetVars.ActiveRoles = pm.GetDefaultRoles(u, h)
			return true
		}
	}
	return false
}

func getHostByIP(ip string) []string {
	if ip == "127.0.0.1" {
		return []string{variable.DefHostname}
	}
	addrs, err := net.LookupAddr(ip)
	if err != nil {
		// The error is ignorable.
		// The empty line here makes the golint tool (which complains err is not checked) happy.
	}
	return addrs
}

// CreateCausetnet4Test creates a new causetnet environment for test.
func CreateCausetnet4Test(store ekv.Storage) (Causetnet, error) {
	return CreateCausetnet4TestWithOpt(store, nil)
}

// Opt describes the option for creating causetnet
type Opt struct {
	PreparedPlanCache *kvcache.SimpleLRUCache
}

// CreateCausetnet4TestWithOpt creates a new causetnet environment for test.
func CreateCausetnet4TestWithOpt(store ekv.Storage, opt *Opt) (Causetnet, error) {
	s, err := CreateCausetnetWithOpt(store, opt)
	if err == nil {
		// initialize causetnet variables for test.
		s.GetCausetnetVars().InitChunkSize = 2
		s.GetCausetnetVars().MaxChunkSize = 32
	}
	return s, err
}

// CreateCausetnet creates a new causetnet environment.
func CreateCausetnet(store ekv.Storage) (Causetnet, error) {
	return CreateCausetnetWithOpt(store, nil)
}

// CreateCausetnetWithOpt creates a new causetnet environment with option.
// Use default option if opt is nil.
func CreateCausetnetWithOpt(store ekv.Storage, opt *Opt) (Causetnet, error) {
	s, err := createCausetnetWithOpt(store, opt)
	if err != nil {
		return nil, err
	}

	// Add auth here.
	do, err := domap.Get(store)
	if err != nil {
		return nil, err
	}
	pm := &privileges.UserPrivileges{
		Handle: do.PrivilegeHandle(),
	}
	privilege.BindPrivilegeManager(s, pm)

	causetnetBindHandle := bindinfo.NewCausetnetBindHandle(s.BerolinaSQL)
	s.SetValue(bindinfo.CausetnetBindInfoKeyType, causetnetBindHandle)
	// Add stats collector, and it will be freed by background stats leasee_parity_filter
	// which periodically updates stats using the collected data.
	if do.StatsHandle() != nil && do.StatsUpdating() {
		s.statsCollector = do.StatsHandle().NewCausetnetStatsCollector()
	}

	return s, nil
}

// loadSystemTZ loads systemTZ from mysql.MilevaDB
func loadSystemTZ(se *causetnet) (string, error) {
	return loadParameter(se, "system_tz")
}

// loadCollationParameter loads collation parameter from mysql.MilevaDB
func loadCollationParameter(se *causetnet) (bool, error) {
	para, err := loadParameter(se, MilevaDBNewCollationEnabled)
	if err != nil {
		return false, err
	}
	if para == varTrue {
		return true, nil
	} else if para == varFalse {
		return false, nil
	}
	logutil.BgLogger().Warn(
		"Unexpected value of 'new_collation_enabled' in 'mysql.MilevaDB', use 'False' instead",
		zap.String("value", para))
	return false, nil
}

// loadParameter loads read-only parameter from mysql.MilevaDB
func loadParameter(se *causetnet, name string) (string, error) {
	sql := "select variable_value from mysql.MilevaDB where variable_name = '" + name + "'"
	rss, errLoad := se.Execute(context.Background(), sql)
	if errLoad != nil {
		return "", errLoad
	}
	// the record of mysql.MilevaDB under where condition: variable_name = $name should shall only be one.
	defer func() {
		if err := rss[0].Close(); err != nil {
			logutil.BgLogger().Error("close result set error", zap.Error(err))
		}
	}()
	req := rss[0].NewChunk()
	if err := rss[0].Next(context.Background(), req); err != nil {
		return "", err
	}
	return req.GetRow(0).GetString(0), nil
}

// BootstrapCausetnet runs the first time when the MilevaDB server start.
func BootstrapCausetnet(store ekv.Storage) (*domain.Domain, error) {
	cfg := config.GetGlobalConfig()
	if len(cfg.Plugin.Load) > 0 {
		err := plugin.Load(context.Background(), plugin.Config{
			Plugins:        strings.Split(cfg.Plugin.Load, ","),
			PluginDir:      cfg.Plugin.Dir,
			GlobalSysVar:   &variable.SysVars,
			PluginVarNames: &variable.PluginVarNames,
		})
		if err != nil {
			return nil, err
		}
	}

	initLoadCommonGlobalVarsSQL()

	ver := getStoreBootstrapVersion(store)
	if ver == notBootstrapped {
		runInBootstrapCausetnet(store, bootstrap)
	} else if ver < currentBootstrapVersion {
		runInBootstrapCausetnet(store, upgrade)
	}

	se, err := createCausetnet(store)
	if err != nil {
		return nil, err
	}
	// get system tz from mysql.MilevaDB
	tz, err := loadSystemTZ(se)
	if err != nil {
		return nil, err
	}
	timeutil.SetSystemTZ(tz)

	// get the flag from `mysql`.`MilevaDB` which indicating if new collations are enabled.
	newCollationEnabled, err := loadCollationParameter(se)
	if err != nil {
		return nil, err
	}

	if newCollationEnabled {
		collate.EnableNewCollations()
	}

	dom := domain.GetDomain(se)
	dom.InitExpensiveQueryHandle()

	se2, err := createCausetnet(store)
	if err != nil {
		return nil, err
	}
	se3, err := createCausetnet(store)
	if err != nil {
		return nil, err
	}
	// We should make the load bind-info loop before other loops which has internal SQL.
	// Because the internal SQL may access the global bind-info handler. As the result, the data race occurs here as the
	// LoadBindInfoLoop inits global bind-info handler.
	err = dom.LoadBindInfoLoop(se2, se3)
	if err != nil {
		return nil, err
	}

	if !config.GetGlobalConfig().Security.SkipGrantTable {
		err = dom.LoadPrivilegeLoop(se)
		if err != nil {
			return nil, err
		}
	}

	if len(cfg.Plugin.Load) > 0 {
		err := plugin.Init(context.Background(), plugin.Config{EtcdClient: dom.GetEtcdClient()})
		if err != nil {
			return nil, err
		}
	}

	err = Interlock.LoadExprPushdownBlacklist(se)
	if err != nil {
		return nil, err
	}

	err = Interlock.LoadOptRuleBlacklist(se)
	if err != nil {
		return nil, err
	}

	dom.TelemetryLoop(se)

	se1, err := createCausetnet(store)
	if err != nil {
		return nil, err
	}
	err = dom.UpdateTableStatsLoop(se1)
	if err != nil {
		return nil, err
	}
	if raw, ok := store.(einsteindb.EtcdBackend); ok {
		err = raw.StartGCleasee_parity_filter()
		if err != nil {
			return nil, err
		}
	}

	return dom, err
}

// GetDomain gets the associated domain for store.
func GetDomain(store ekv.Storage) (*domain.Domain, error) {
	return domap.Get(store)
}

// runInBootstrapCausetnet create a special causetnet for bootstrap to run.
// If no bootstrap and storage is remote, we must use a little lease time to
// bootstrap quickly, after bootstrapped, we will reset the lease time.
// TODO: Using a bootstrap tool for doing this may be better later.
func runInBootstrapCausetnet(store ekv.Storage, bootstrap func(Causetnet)) {
	s, err := createCausetnet(store)
	if err != nil {
		// Bootstrap fail will cause program exit.
		logutil.BgLogger().Fatal("createCausetnet error", zap.Error(err))
	}

	s.SetValue(causetnetctx.Initing, true)
	bootstrap(s)
	finishBootstrap(store)
	s.ClearValue(causetnetctx.Initing)

	dom := domain.GetDomain(s)
	dom.Close()
	domap.Delete(store)
}

func createCausetnet(store ekv.Storage) (*causetnet, error) {
	return createCausetnetWithOpt(store, nil)
}

func createCausetnetWithOpt(store ekv.Storage, opt *Opt) (*causetnet, error) {
	dom, err := domap.Get(store)
	if err != nil {
		return nil, err
	}
	s := &causetnet{
		store:           store,
		BerolinaSQL:     BerolinaSQL.New(),
		causetnetVars:   variable.NewCausetnetVars(),
		ddlOwnerChecker: dom.DDL().OwnerManager(),
		client:          store.GetClient(),
	}
	if plannercore.PreparedPlanCacheEnabled() {
		if opt != nil && opt.PreparedPlanCache != nil {
			s.preparedPlanCache = opt.PreparedPlanCache
		} else {
			s.preparedPlanCache = kvcache.NewSimpleLRUCache(plannercore.PreparedPlanCacheCapacity,
				plannercore.PreparedPlanCacheMemoryGuardRatio, plannercore.PreparedPlanCacheMaxMemory.Load())
		}
	}
	s.mu.values = make(map[fmt.Stringer]interface{})
	s.lockedTables = make(map[int64]serial.TableLockTpInfo)
	domain.BindDomain(s, dom)
	// causetnet implements variable.GlobalVarAccessor. Bind it to ctx.
	s.causetnetVars.GlobalVarsAccessor = s
	s.causetnetVars.BinlogClient = binloginfo.GetPumpsClient()
	s.txn.init()

	causetnetBindHandle := bindinfo.NewCausetnetBindHandle(s.BerolinaSQL)
	s.SetValue(bindinfo.CausetnetBindInfoKeyType, causetnetBindHandle)
	return s, nil
}

// CreateCausetnetWithDomain creates a new Causetnet and binds it with a Domain.
// We need this because when we start DDL in Domain, the DDL need a causetnet
// to change some system blocks. But at that time, we have been already in
// a dagger context, which cause we can't call createSesion directly.
func CreateCausetnetWithDomain(store ekv.Storage, dom *domain.Domain) (*causetnet, error) {
	s := &causetnet{
		store:         store,
		BerolinaSQL:   BerolinaSQL.New(),
		causetnetVars: variable.NewCausetnetVars(),
		client:        store.GetClient(),
	}
	if plannercore.PreparedPlanCacheEnabled() {
		s.preparedPlanCache = kvcache.NewSimpleLRUCache(plannercore.PreparedPlanCacheCapacity,
			plannercore.PreparedPlanCacheMemoryGuardRatio, plannercore.PreparedPlanCacheMaxMemory.Load())
	}
	s.mu.values = make(map[fmt.Stringer]interface{})
	s.lockedTables = make(map[int64]serial.TableLockTpInfo)
	domain.BindDomain(s, dom)
	// causetnet implements variable.GlobalVarAccessor. Bind it to ctx.
	s.causetnetVars.GlobalVarsAccessor = s
	s.txn.init()
	return s, nil
}

const (
	notBootstrapped         = 0
	currentBootstrapVersion = version48
)

func getStoreBootstrapVersion(store ekv.Storage) int64 {
	storeBootstrappedLock.Lock()
	defer storeBootstrappedLock.Unlock()
	// check in memory
	_, ok := storeBootstrapped[store.UUID()]
	if ok {
		return currentBootstrapVersion
	}

	var ver int64
	// check in ekv store
	err := ekv.RunInNewTxn(store, false, func(txn ekv.Transaction) error {
		var err error
		t := meta.NewMeta(txn)
		ver, err = t.GetBootstrapVersion()
		return err
	})

	if err != nil {
		logutil.BgLogger().Fatal("check bootstrapped failed",
			zap.Error(err))
	}

	if ver > notBootstrapped {
		// here mean memory is not ok, but other server has already finished it
		storeBootstrapped[store.UUID()] = true
	}

	return ver
}

func finishBootstrap(store ekv.Storage) {
	setStoreBootstrapped(store.UUID())

	err := ekv.RunInNewTxn(store, true, func(txn ekv.Transaction) error {
		t := meta.NewMeta(txn)
		err := t.FinishBootstrap(currentBootstrapVersion)
		return err
	})
	if err != nil {
		logutil.BgLogger().Fatal("finish bootstrap failed",
			zap.Error(err))
	}
}

const quoteCommaQuote = "', '"

var builtinGlobalVariable = []string{
	variable.AutoCommit,
	variable.SQLModeVar,
	variable.MaxAllowedPacket,
	variable.TimeZone,
	variable.BlockEncryptionMode,
	variable.WaitTimeout,
	variable.InteractiveTimeout,
	variable.MaxPreparedStmtCount,
	variable.InitConnect,
	variable.TxnIsolation,
	variable.TxReadOnly,
	variable.TransactionIsolation,
	variable.TransactionReadOnly,
	variable.NetBufferLength,
	variable.QueryCacheType,
	variable.QueryCacheSize,
	variable.CharacterSetServer,
	variable.AutoIncrementIncrement,
	variable.AutoIncrementOffset,
	variable.CollationServer,
	variable.NetWriteTimeout,
	variable.MaxExecutionTime,
	variable.InnodbLockWaitTimeout,
	variable.WindowingUseHighPrecision,
	variable.SQLSelectLimit,

	/* MilevaDB specific global variables: */
	variable.MilevaDBSkipASCIICheck,
	variable.MilevaDBSkipUTF8Check,
	variable.MilevaDBIndexJoinBatchSize,
	variable.MilevaDBIndexLookupSize,
	variable.MilevaDBIndexLookupConcurrency,
	variable.MilevaDBIndexLookupJoinConcurrency,
	variable.MilevaDBIndexSerialScanConcurrency,
	variable.MilevaDBHashJoinConcurrency,
	variable.MilevaDBProjectionConcurrency,
	variable.MilevaDBHashAggPartialConcurrency,
	variable.MilevaDBHashAggFinalConcurrency,
	variable.MilevaDBWindowConcurrency,
	variable.MilevaDBInterlockConcurrency,
	variable.MilevaDBBackoffLockFast,
	variable.MilevaDBBackOffWeight,
	variable.MilevaDBConstraintCheckInPlace,
	variable.MilevaDBDDLReorgleasee_parity_filterCount,
	variable.MilevaDBDDLReorgBatchSize,
	variable.MilevaDBDDLErrorCountLimit,
	variable.MilevaDBOptInSubqToJoinAndAgg,
	variable.MilevaDBOptCorrelationThreshold,
	variable.MilevaDBOptCorrelationExpFactor,
	variable.MilevaDBOptCPUFactor,
	variable.MilevaDBOptINTERLOCKCPUFactor,
	variable.MilevaDBOptNetworkFactor,
	variable.MilevaDBOptScanFactor,
	variable.MilevaDBOptDescScanFactor,
	variable.MilevaDBOptMemoryFactor,
	variable.MilevaDBOptDiskFactor,
	variable.MilevaDBOptConcurrencyFactor,
	variable.MilevaDBDistSQLScanConcurrency,
	variable.MilevaDBInitChunkSize,
	variable.MilevaDBMaxChunkSize,
	variable.MilevaDBEnableCascadesPlanner,
	variable.MilevaDBRetryLimit,
	variable.MilevaDBDisableTxnAutoRetry,
	variable.MilevaDBEnableWindowFunction,
	variable.MilevaDBEnableTablePartition,
	variable.MilevaDBEnableVectorizedExpression,
	variable.MilevaDBEnableFastAnalyze,
	variable.MilevaDBExpensiveQueryTimeThreshold,
	variable.MilevaDBEnableNoopFuncs,
	variable.MilevaDBEnableIndexMerge,
	variable.MilevaDBTxnMode,
	variable.MilevaDBAllowBatchINTERLOCK,
	variable.MilevaDBRowFormatVersion,
	variable.MilevaDBEnableStmtSummary,
	variable.MilevaDBStmtSummaryInternalQuery,
	variable.MilevaDBStmtSummaryRefreshInterval,
	variable.MilevaDBStmtSummaryHistorySize,
	variable.MilevaDBStmtSummaryMaxStmtCount,
	variable.MilevaDBStmtSummaryMaxSQLLength,
	variable.MilevaDBMaxDeltaSchemaCount,
	variable.MilevaDBCapturePlanBaseline,
	variable.MilevaDBUsePlanBaselines,
	variable.MilevaDBEvolvePlanBaselines,
	variable.MilevaDBIsolationReadEngines,
	variable.MilevaDBStoreLimit,
	variable.MilevaDBAllowAutoRandExplicitInsert,
	variable.MilevaDBEnableClusteredIndex,
	variable.MilevaDBSlowLogMasking,
	variable.MilevaDBEnableTelemetry,
	variable.MilevaDBShardAllocateStep,
}

var (
	loadCommonGlobalVarsSQLOnce sync.Once
	loadCommonGlobalVarsSQL     string
)

func initLoadCommonGlobalVarsSQL() {
	loadCommonGlobalVarsSQLOnce.Do(func() {
		vars := append(make([]string, 0, len(builtinGlobalVariable)+len(variable.PluginVarNames)), builtinGlobalVariable...)
		if len(variable.PluginVarNames) > 0 {
			vars = append(vars, variable.PluginVarNames...)
		}
		loadCommonGlobalVarsSQL = "select HIGH_PRIORITY * from mysql.global_variables where variable_name in ('" + strings.Join(vars, quoteCommaQuote) + "')"
	})
}

// loadCommonGlobalVariablesIfNeeded loads and applies commonly used global variables for the causetnet.
func (s *causetnet) loadCommonGlobalVariablesIfNeeded() error {
	initLoadCommonGlobalVarsSQL()
	vars := s.causetnetVars
	if vars.CommonGlobalLoaded {
		return nil
	}
	if s.Value(causetnetctx.Initing) != nil {
		// When running bootstrap or upgrade, we should not access global storage.
		return nil
	}

	var err error
	// Use GlobalVariableCache if MilevaDB just loaded global variables within 2 second ago.
	// When a lot of connections connect to MilevaDB simultaneously, it can protect EinsteinDB meta region from overload.
	gvc := domain.GetDomain(s).GetGlobalVarsCache()
	loadFunc := func() ([]chunk.Row, []*ast.ResultField, error) {
		return s.ExecRestrictedSQL(loadCommonGlobalVarsSQL)
	}
	rows, fields, err := gvc.LoadGlobalVariables(loadFunc)
	if err != nil {
		logutil.BgLogger().Warn("failed to load global variables",
			zap.Uint64("conn", s.causetnetVars.ConnectionID), zap.Error(err))
		return err
	}
	vars.CommonGlobalLoaded = true

	for _, row := range rows {
		varName := row.GetString(0)
		varVal := row.GetCausetObjectQL(1, &fields[1].Column.FieldType)
		if _, ok := vars.GetSystemVar(varName); !ok {
			err = variable.SetCausetnetSystemVar(s.causetnetVars, varName, varVal)
			if err != nil {
				return err
			}
		}
	}

	// when client set Capability Flags CLIENT_INTERACTIVE, init wait_timeout with interactive_timeout
	if vars.ClientCapability&mysql.ClientInteractive > 0 {
		if varVal, ok := vars.GetSystemVar(variable.InteractiveTimeout); ok {
			if err := vars.SetSystemVar(variable.WaitTimeout, varVal); err != nil {
				return err
			}
		}
	}

	vars.CommonGlobalLoaded = true
	return nil
}

// PrepareTxnCtx starts a goroutine to begin a transaction if needed, and creates a new transaction context.
// It is called before we execute a sql query.
func (s *causetnet) PrepareTxnCtx(ctx context.Context) {
	if s.txn.validOrPending() {
		return
	}

	is := domain.GetDomain(s).schemareplicant()
	s.causetnetVars.TxnCtx = &variable.TransactionContext{
		schemareplicant: is,
		SchemaVersion:   is.SchemaMetaVersion(),
		CreateTime:      time.Now(),
		ShardStep:       int(s.causetnetVars.ShardAllocateStep),
	}
	if !s.causetnetVars.IsAutocommit() {
		pessTxnConf := config.GetGlobalConfig().PessimisticTxn
		if pessTxnConf.Enable {
			if s.causetnetVars.TxnMode == ast.Pessimistic {
				s.causetnetVars.TxnCtx.IsPessimistic = true
			}
		}
	}
}

// PrepareTSFuture uses to try to get ts future.
func (s *causetnet) PrepareTSFuture(ctx context.Context) {
	if !s.txn.validOrPending() {
		// Prepare the transaction future if the transaction is invalid (at the beginning of the transaction).
		txnFuture := s.getTxnFuture(ctx)
		s.txn.changeInvalidToPending(txnFuture)
	} else if s.txn.Valid() && s.GetCausetnetVars().IsPessimisticReadConsistency() {
		// Prepare the statement future if the transaction is valid in RC transactions.
		s.GetCausetnetVars().TxnCtx.SetStmtFutureForRC(s.getTxnFuture(ctx).future)
	}
}

// RefreshTxnCtx implements context.RefreshTxnCtx interface.
func (s *causetnet) RefreshTxnCtx(ctx context.Context) error {
	if err := s.doCommit(ctx); err != nil {
		return err
	}

	return s.NewTxn(ctx)
}

// InitTxnWithStartTS create a transaction with startTS.
func (s *causetnet) InitTxnWithStartTS(startTS uint64) error {
	if s.txn.Valid() {
		return nil
	}

	// no need to get txn from txnFutureCh since txn should init with startTs
	txn, err := s.store.BeginWithStartTS(startTS)
	if err != nil {
		return err
	}
	s.txn.changeInvalidToValid(txn)
	err = s.loadCommonGlobalVariablesIfNeeded()
	if err != nil {
		return err
	}
	return nil
}

// GetStore gets the store of causetnet.
func (s *causetnet) GetStore() ekv.Storage {
	return s.store
}

func (s *causetnet) ShowProcess() *util.ProcessInfo {
	var pi *util.ProcessInfo
	tmp := s.processInfo.Load()
	if tmp != nil {
		pi = tmp.(*util.ProcessInfo)
	}
	return pi
}

// logStmt logs some crucial SQL including: CREATE USER/GRANT PRIVILEGE/CHANGE PASSWORD/DDL etc and normal SQL
// if variable.ProcessGeneralLog is set.
func logStmt(node ast.StmtNode, vars *variable.CausetnetVars) {
	switch stmt := node.(type) {
	case *ast.CreateUserStmt, *ast.DropUserStmt, *ast.AlterUserStmt, *ast.SetPwdStmt, *ast.GrantStmt,
		*ast.RevokeStmt, *ast.AlterTableStmt, *ast.CreateDatabaseStmt, *ast.CreateIndexStmt, *ast.CreateTableStmt,
		*ast.DropDatabaseStmt, *ast.DropIndexStmt, *ast.DropTableStmt, *ast.RenameTableStmt, *ast.TruncateTableStmt:
		user := vars.User
		schemaVersion := vars.TxnCtx.SchemaVersion
		if ss, ok := node.(ast.SensitiveStmtNode); ok {
			logutil.BgLogger().Info("CRUCIAL OPERATION",
				zap.Uint64("conn", vars.ConnectionID),
				zap.Int64("schemaVersion", schemaVersion),
				zap.String("secure text", ss.SecureText()),
				zap.Stringer("user", user))
		} else {
			logutil.BgLogger().Info("CRUCIAL OPERATION",
				zap.Uint64("conn", vars.ConnectionID),
				zap.Int64("schemaVersion", schemaVersion),
				zap.String("cur_db", vars.CurrentDB),
				zap.String("sql", stmt.Text()),
				zap.Stringer("user", user))
		}
	default:
		logQuery(node.Text(), vars)
	}
}

func logQuery(query string, vars *variable.CausetnetVars) {
	if atomic.LoadUint32(&variable.ProcessGeneralLog) != 0 && !vars.InRestrictedSQL {
		query = Interlock.QueryReplacer.Replace(query)
		logutil.BgLogger().Info("GENERAL_LOG",
			zap.Uint64("conn", vars.ConnectionID),
			zap.Stringer("user", vars.User),
			zap.Int64("schemaVersion", vars.TxnCtx.SchemaVersion),
			zap.Uint64("txnStartTS", vars.TxnCtx.StartTS),
			zap.Uint64("forUpdateTS", vars.TxnCtx.GetForUpdateTS()),
			zap.Bool("isReadConsistency", vars.IsReadConsistencyTxn()),
			zap.String("current_db", vars.CurrentDB),
			zap.String("txn_mode", vars.GetReadableTxnMode()),
			zap.String("sql", query+vars.PreparedParams.String()))
	}
}

func (s *causetnet) recordOnTransactionExecution(err error, counter int, duration float64) {
	if s.causetnetVars.TxnCtx.IsPessimistic {
		if err != nil {
			statementPerTransactionPessimisticError.Observe(float64(counter))
			transactionDurationPessimisticAbort.Observe(duration)
		} else {
			statementPerTransactionPessimisticOK.Observe(float64(counter))
			transactionDurationPessimisticCommit.Observe(duration)
		}
	} else {
		if err != nil {
			statementPerTransactionOptimisticError.Observe(float64(counter))
			transactionDurationOptimisticAbort.Observe(duration)
		} else {
			statementPerTransactionOptimisticOK.Observe(float64(counter))
			transactionDurationOptimisticCommit.Observe(duration)
		}
	}
}
